DROP TYPE KDSADMIN.OBJ_SHGIOT_MEUSHAROT;

CREATE OR REPLACE TYPE KDSADMIN.OBJ_SHGIOT_MEUSHAROT as object 
    (MISPAR_ISHI number (9), KOD_SHGIA number(5),TAARICH date,
    MISPAR_SIDUR number(6),SHAT_HATCHALA date,SHAT_YETZIA date,
    MISPAR_KNISA number, GOREM_MEASHER number(9),
    TAARICH_ISHUR date,HEARA varchar2(100))