//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KdsLibrary.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class COLL_IDKUN_RASHEMET : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        private int _Count;
        private OBJ_IDKUN_RASHEMET[] m_OBJ_IDKUN_RASHEMET;
        
        public COLL_IDKUN_RASHEMET() {
            // TODO : Add code to initialise the object
        }
        
        public COLL_IDKUN_RASHEMET(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        public int Count
        {
            get
            {
                return this._Count;
            }
        }
        public static COLL_IDKUN_RASHEMET Null {
            get {
                COLL_IDKUN_RASHEMET obj = new COLL_IDKUN_RASHEMET();
                obj.m_IsNull = true;
                return obj;
            }
        }
        public void Add(OBJ_IDKUN_RASHEMET Object)
        {
            if (Object.IsNull) return;
            int Size;
            if (m_OBJ_IDKUN_RASHEMET == null)
            {
                m_OBJ_IDKUN_RASHEMET = new OBJ_IDKUN_RASHEMET[1];
                m_OBJ_IDKUN_RASHEMET[0] = Object;
            }
            else
            {
                Size = m_OBJ_IDKUN_RASHEMET.Length;
                m_OBJ_IDKUN_RASHEMET = (OBJ_IDKUN_RASHEMET[])clGeneral.ResizeArray(m_OBJ_IDKUN_RASHEMET, Size + 1);
                m_OBJ_IDKUN_RASHEMET[Size] = Object;
            }
            _Count = m_OBJ_IDKUN_RASHEMET.Length;
        }
        [OracleArrayMappingAttribute()]
        public virtual OBJ_IDKUN_RASHEMET[] Value {
            get {
                return this.m_OBJ_IDKUN_RASHEMET;
            }
            set {
                this.m_OBJ_IDKUN_RASHEMET = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            OracleUdt.SetValue(con, pUdt, 0, this.m_OBJ_IDKUN_RASHEMET);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.m_OBJ_IDKUN_RASHEMET = ((OBJ_IDKUN_RASHEMET[])(OracleUdt.GetValue(con, pUdt, 0)));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static COLL_IDKUN_RASHEMET Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new COLL_IDKUN_RASHEMET();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.COLL_IDKUN_RASHEMET")]
    public class COLL_IDKUN_RASHEMETFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            COLL_IDKUN_RASHEMET obj = new COLL_IDKUN_RASHEMET();
            return obj;
        }
        
        public virtual System.Array CreateArray(int length) {
            OBJ_IDKUN_RASHEMET[] collElem = new OBJ_IDKUN_RASHEMET[length];
            return collElem;
        }
        
        public virtual System.Array CreateStatusArray(int length) {
            return null;
        }
    }
}
