//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSCommon.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    using KDSCommon.Helpers;
    
    public class COLL_SHGIOT_MEUSHAROT : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        private int _Count;
        private OBJ_SHGIOT_MEUSHAROT[] m_OBJ_SHGIOT_MEUSHAROT;
        
        public COLL_SHGIOT_MEUSHAROT() {
            // TODO : Add code to initialise the object
        }
        
        public COLL_SHGIOT_MEUSHAROT(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        public int Count
        {
            get
            {
                return this._Count;
            }
        }
        public void Add(OBJ_SHGIOT_MEUSHAROT Object)
        {
            if (Object.IsNull) return;

            int Size;
            if (m_OBJ_SHGIOT_MEUSHAROT == null)
            {
                m_OBJ_SHGIOT_MEUSHAROT = new OBJ_SHGIOT_MEUSHAROT[1];
                m_OBJ_SHGIOT_MEUSHAROT[0] = Object;
            }
            else
            {
                Size = m_OBJ_SHGIOT_MEUSHAROT.Length;
                m_OBJ_SHGIOT_MEUSHAROT = (OBJ_SHGIOT_MEUSHAROT[])ArrayHelper.ResizeArray(m_OBJ_SHGIOT_MEUSHAROT, Size + 1);
                m_OBJ_SHGIOT_MEUSHAROT[Size] = Object;
            }
            _Count = m_OBJ_SHGIOT_MEUSHAROT.Length;
        }
        public static COLL_SHGIOT_MEUSHAROT Null {
            get {
                COLL_SHGIOT_MEUSHAROT obj = new COLL_SHGIOT_MEUSHAROT();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleArrayMappingAttribute()]
        public virtual OBJ_SHGIOT_MEUSHAROT[] Value {
            get {
                return this.m_OBJ_SHGIOT_MEUSHAROT;
            }
            set {
                this.m_OBJ_SHGIOT_MEUSHAROT = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            OracleUdt.SetValue(con, pUdt, 0, this.m_OBJ_SHGIOT_MEUSHAROT);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.m_OBJ_SHGIOT_MEUSHAROT = ((OBJ_SHGIOT_MEUSHAROT[])(OracleUdt.GetValue(con, pUdt, 0)));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static COLL_SHGIOT_MEUSHAROT Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new COLL_SHGIOT_MEUSHAROT();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.COLL_SHGIOT_MEUSHAROT")]
    public class COLL_SHGIOT_MEUSHAROTFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            COLL_SHGIOT_MEUSHAROT obj = new COLL_SHGIOT_MEUSHAROT();
            return obj;
        }
        
        public virtual System.Array CreateArray(int length) {
            OBJ_SHGIOT_MEUSHAROT[] collElem = new OBJ_SHGIOT_MEUSHAROT[length];
            return collElem;
        }
        
        public virtual System.Array CreateStatusArray(int length) {
            return null;
        }
    }

}
