//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSCommon.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
     
    public class OBJ_Harmony_movment_Err_Mov : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private System.DateTime m_HOUR;
        
        private bool m_HOURIsNull;
        
        private float m_CHANG_REC;
        
        private bool m_CHANG_RECIsNull;
        
        private string m_MARKED;
        
        private string m_PARAM3;
        
        private float m_SHIFT;
        
        private bool m_SHIFTIsNull;
        
        private System.DateTime m_TAARICH_MEADKEN_ACHARON;
        
        private bool m_TAARICH_MEADKEN_ACHARONIsNull;
        
        private string m_PARAM6;
        
        private float m_MEADKEN_ACHARON;
        
        private bool m_MEADKEN_ACHARONIsNull;
        
        private System.DateTime m_ABSTIME;
        
        private bool m_ABSTIMEIsNull;
             
        private string m_CODEORG;
        
        private float m_DUP_REC;
        
        private bool m_DUP_RECIsNull;
        
        private string m_ACTION;
        
        private string m_PARAM5;
        
        private string m_ALTERNATIVE;
        
        private string m_DESCR;
        
        private string m_CAR_NO;
        
        private float m_CODE_ERR;
        
        private bool m_CODE_ERRIsNull;
        
        private System.DateTime m_DATETRANSF;
        
        private bool m_DATETRANSFIsNull;
        
        private System.DateTime m_REC_ENTER;
        
        private bool m_REC_ENTERIsNull;
        
        private float m_ZIGNORE;
        
        private bool m_ZIGNOREIsNull;
        
        private string m_TRAILER1_BADGE;
        
        private string m_LANCH;
        
        private float m_BED;
        
        private bool m_BEDIsNull;
        
        private float m_L_PRESENT;
        
        private bool m_L_PRESENTIsNull;
        
        private string m_MACHINE_W;
        
        private float m_EMP_NO;
        
        private bool m_EMP_NOIsNull;
        
        private string m_CAR_BADGE;
        
        private float m_ERR_MOVID;
        
        private bool m_ERR_MOVIDIsNull;
        
        private float m_NO_TMP_ACTIVITY;
        
        private bool m_NO_TMP_ACTIVITYIsNull;
        
        private string m_SITE;
        
        private string m_STATION;
        
        private float m_CLOCKID;
        
        private bool m_CLOCKIDIsNull;
        
        private float m_MEAL_SUPP;
        
        private bool m_MEAL_SUPPIsNull;
        
        private string m_MAKOR;
        
        private float m_AUTHORIZED;
        
        private bool m_AUTHORIZEDIsNull;
        
        private string m_MACHINE;
        
        private string m_EXCEP;
        
        private System.DateTime m_TAARICH;
        
        private bool m_TAARICHIsNull;
        
        private string m_TRAILER_BADGE;
        
        private float m_GOOD;
        
        private bool m_GOODIsNull;
        
        private string m_PARAM2;
        
        private float m_MEAL_QUANT;
        
        private bool m_MEAL_QUANTIsNull;
        
        private string m_OPER;
        
        private string m_TRAILER_NO;
        
        private string m_XLEVEL;
        
        private float m_LEVELORG;
        
        private bool m_LEVELORGIsNull;
        
        private float m_FROM_DLL;
        
        private bool m_FROM_DLLIsNull;
        
        private string m_PARAM1;
        
        private float m_GOOD_REC;
        
        private bool m_GOOD_RECIsNull;
        
        private string m_PRODUCT;
        
        private string m_PARAM4;
        
        private string m_EXECUTED;
        
        private float m_BADGE_TYPE;
        
        private bool m_BADGE_TYPEIsNull;
        
        private string m_TRAILER1_NO;
        
        private string m_STATION_W;
        
        private float m_HAND;
        
        private bool m_HANDIsNull;
        
        private string m_BADGE;
        
        private float m_EXPORT_P;
        
        private bool m_EXPORT_PIsNull;
        
        private string m_UNITPROD;
        
        private string m_ABSCODE;
        
        private float m_NO_ACTIVITY;
        
        private bool m_NO_ACTIVITYIsNull;
        
        private string m_CODE;
        
        public OBJ_Harmony_movment_Err_Mov() {
            // TODO : Add code to initialise the object
            this.m_HOURIsNull = true;
            this.m_CHANG_RECIsNull = true;
            this.m_SHIFTIsNull = true;
            this.m_TAARICH_MEADKEN_ACHARONIsNull = true;
            this.m_MEADKEN_ACHARONIsNull = true;
            this.m_ABSTIMEIsNull = true;
            this.m_DUP_RECIsNull = true;
            this.m_CODE_ERRIsNull = true;
            this.m_DATETRANSFIsNull = true;
            this.m_REC_ENTERIsNull = true;
            this.m_ZIGNOREIsNull = true;
            this.m_BEDIsNull = true;
            this.m_L_PRESENTIsNull = true;
            this.m_EMP_NOIsNull = true;
            this.m_ERR_MOVIDIsNull = true;
            this.m_NO_TMP_ACTIVITYIsNull = true;
            this.m_CLOCKIDIsNull = true;
            this.m_MEAL_SUPPIsNull = true;
            this.m_AUTHORIZEDIsNull = true;
            this.m_TAARICHIsNull = true;
            this.m_GOODIsNull = true;
            this.m_MEAL_QUANTIsNull = true;
            this.m_LEVELORGIsNull = true;
            this.m_FROM_DLLIsNull = true;
            this.m_GOOD_RECIsNull = true;
            this.m_BADGE_TYPEIsNull = true;
            this.m_HANDIsNull = true;
            this.m_EXPORT_PIsNull = true;
            this.m_NO_ACTIVITYIsNull = true;
        }
        
        public OBJ_Harmony_movment_Err_Mov(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static OBJ_Harmony_movment_Err_Mov Null {
            get {
                OBJ_Harmony_movment_Err_Mov obj = new OBJ_Harmony_movment_Err_Mov();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("HOUR")]
        public System.DateTime HOUR {
            get {
                return this.m_HOUR;
            }
            set {
                this.m_HOUR = value;
                this.m_HOURIsNull = false;  
            }
        }
        
        public bool HOURIsNull {
            get {
                return this.m_HOURIsNull;
            }
            set {
                this.m_HOURIsNull = value;  
            }
        }
        
        [OracleObjectMappingAttribute("CHANG_REC")]
        public float CHANG_REC {
            get {
                return this.m_CHANG_REC;
            }
            set {
                this.m_CHANG_REC = value;
                this.m_CHANG_RECIsNull = false;  
            }
        }
        
        public bool CHANG_RECIsNull {
            get {
                return this.m_CHANG_RECIsNull;
            }
            set {
                this.m_CHANG_RECIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MARKED")]
        public string MARKED {
            get {
                return this.m_MARKED;
            }
            set {
                this.m_MARKED = value;         
            }
        }
        
        [OracleObjectMappingAttribute("PARAM3")]
        public string PARAM3 {
            get {
                return this.m_PARAM3;
            }
            set {
                this.m_PARAM3 = value;
            }
        }
        
        [OracleObjectMappingAttribute("SHIFT")]
        public float SHIFT {
            get {
                return this.m_SHIFT;
            }
            set {
                this.m_SHIFT = value;
                this.m_SHIFTIsNull = false;
            }
        }
        
        public bool SHIFTIsNull {
            get {
                return this.m_SHIFTIsNull;
            }
            set {
                this.m_SHIFTIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("TAARICH_MEADKEN_ACHARON")]
        public System.DateTime TAARICH_MEADKEN_ACHARON {
            get {
                return this.m_TAARICH_MEADKEN_ACHARON;
            }
            set {
                this.m_TAARICH_MEADKEN_ACHARON = value;
                this.m_TAARICH_MEADKEN_ACHARONIsNull = false;
            }
        }
        
        public bool TAARICH_MEADKEN_ACHARONIsNull {
            get {
                return this.m_TAARICH_MEADKEN_ACHARONIsNull;
            }
            set {
                this.m_TAARICH_MEADKEN_ACHARONIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("PARAM6")]
        public string PARAM6 {
            get {
                return this.m_PARAM6;
            }
            set {
                this.m_PARAM6 = value;
            }
        }
        
        [OracleObjectMappingAttribute("MEADKEN_ACHARON")]
        public float MEADKEN_ACHARON {
            get {
                return this.m_MEADKEN_ACHARON;
            }
            set {
                this.m_MEADKEN_ACHARON = value;
                this.m_MEADKEN_ACHARONIsNull = false;
            }
        }
        
        public bool MEADKEN_ACHARONIsNull {
            get {
                return this.m_MEADKEN_ACHARONIsNull;
            }
            set {
                this.m_MEADKEN_ACHARONIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ABSTIME")]
        public System.DateTime ABSTIME {
            get {
                return this.m_ABSTIME;
            }
            set {
                this.m_ABSTIME = value;
                this.m_ABSTIMEIsNull = false;
            }
        }
        
        public bool ABSTIMEIsNull {
            get {
                return this.m_ABSTIMEIsNull;
            }
            set {
                this.m_ABSTIMEIsNull = value;
            }
        }
        
     
        
        [OracleObjectMappingAttribute("CODEORG")]
        public string CODEORG {
            get {
                return this.m_CODEORG;
            }
            set {
                this.m_CODEORG = value;
            }
        }
        
        [OracleObjectMappingAttribute("DUP_REC")]
        public float DUP_REC {
            get {
                return this.m_DUP_REC;
            }
            set {
                this.m_DUP_REC = value;
                this.m_DUP_RECIsNull = false;
            }
        }
        
        public bool DUP_RECIsNull {
            get {
                return this.m_DUP_RECIsNull;
            }
            set {
                this.m_DUP_RECIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ACTION")]
        public string ACTION {
            get {
                return this.m_ACTION;
            }
            set {
                this.m_ACTION = value;
            }
        }
        
        [OracleObjectMappingAttribute("PARAM5")]
        public string PARAM5 {
            get {
                return this.m_PARAM5;
            }
            set {
                this.m_PARAM5 = value;
            }
        }
        
        [OracleObjectMappingAttribute("ALTERNATIVE")]
        public string ALTERNATIVE {
            get {
                return this.m_ALTERNATIVE;
            }
            set {
                this.m_ALTERNATIVE = value;
            }
        }
        
        [OracleObjectMappingAttribute("DESCR")]
        public string DESCR {
            get {
                return this.m_DESCR;
            }
            set {
                this.m_DESCR = value;
            }
        }
        
        [OracleObjectMappingAttribute("CAR_NO")]
        public string CAR_NO {
            get {
                return this.m_CAR_NO;
            }
            set {
                this.m_CAR_NO = value;
            }
        }
        
        [OracleObjectMappingAttribute("CODE_ERR")]
        public float CODE_ERR {
            get {
                return this.m_CODE_ERR;
            }
            set {
                this.m_CODE_ERR = value;
                this.m_CODE_ERRIsNull = false;
            }
        }
        
        public bool CODE_ERRIsNull {
            get {
                return this.m_CODE_ERRIsNull;
            }
            set {
                this.m_CODE_ERRIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("DATETRANSF")]
        public System.DateTime DATETRANSF {
            get {
                return this.m_DATETRANSF;
            }
            set {
                this.m_DATETRANSF = value;
                this.m_DATETRANSFIsNull = false;
            }
        }
        
        public bool DATETRANSFIsNull {
            get {
                return this.m_DATETRANSFIsNull;
            }
            set {
                this.m_DATETRANSFIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("REC_ENTER")]
        public System.DateTime REC_ENTER {
            get {
                return this.m_REC_ENTER;
            }
            set {
                this.m_REC_ENTER = value;
                this.m_REC_ENTERIsNull = false;
            }
        }
        
        public bool REC_ENTERIsNull {
            get {
                return this.m_REC_ENTERIsNull;
            }
            set {
                this.m_REC_ENTERIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ZIGNORE")]
        public float ZIGNORE {
            get {
                return this.m_ZIGNORE;
            }
            set {
                this.m_ZIGNORE = value;
                this.m_ZIGNOREIsNull = false;
            }
        }
        
        public bool ZIGNOREIsNull {
            get {
                return this.m_ZIGNOREIsNull;
            }
            set {
                this.m_ZIGNOREIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("TRAILER1_BADGE")]
        public string TRAILER1_BADGE {
            get {
                return this.m_TRAILER1_BADGE;
            }
            set {
                this.m_TRAILER1_BADGE = value;
            }
        }
        
        [OracleObjectMappingAttribute("LANCH")]
        public string LANCH {
            get {
                return this.m_LANCH;
            }
            set {
                this.m_LANCH = value;
            }
        }
        
        [OracleObjectMappingAttribute("BED")]
        public float BED {
            get {
                return this.m_BED;
            }
            set {
                this.m_BED = value;
                this.m_BEDIsNull = false;
            }
        }
        
        public bool BEDIsNull {
            get {
                return this.m_BEDIsNull;
            }
            set {
                this.m_BEDIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("L_PRESENT")]
        public float L_PRESENT {
            get {
                return this.m_L_PRESENT;
            }
            set {
                this.m_L_PRESENT = value;
                this.m_L_PRESENTIsNull = false;
            }
        }
        
        public bool L_PRESENTIsNull {
            get {
                return this.m_L_PRESENTIsNull;
            }
            set {
                this.m_L_PRESENTIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MACHINE_W")]
        public string MACHINE_W {
            get {
                return this.m_MACHINE_W;
            }
            set {
                this.m_MACHINE_W = value;
            }
        }
        
        [OracleObjectMappingAttribute("EMP_NO")]
        public float EMP_NO {
            get {
                return this.m_EMP_NO;
            }
            set {
                this.m_EMP_NO = value;
                this.m_EMP_NOIsNull = false;
            }
        }
        
        public bool EMP_NOIsNull {
            get {
                return this.m_EMP_NOIsNull;
            }
            set {
                this.m_EMP_NOIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("CAR_BADGE")]
        public string CAR_BADGE {
            get {
                return this.m_CAR_BADGE;
            }
            set {
                this.m_CAR_BADGE = value;
            }
        }
        
        [OracleObjectMappingAttribute("ERR_MOVID")]
        public float ERR_MOVID {
            get {
                return this.m_ERR_MOVID;
            }
            set {
                this.m_ERR_MOVID = value;
                this.m_ERR_MOVIDIsNull = false;
            }
        }
        
        public bool ERR_MOVIDIsNull {
            get {
                return this.m_ERR_MOVIDIsNull;
            }
            set {
                this.m_ERR_MOVIDIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("NO_TMP_ACTIVITY")]
        public float NO_TMP_ACTIVITY {
            get {
                return this.m_NO_TMP_ACTIVITY;
            }
            set {
                this.m_NO_TMP_ACTIVITY = value;
                this.m_NO_TMP_ACTIVITYIsNull = false;
            }
        }
        
        public bool NO_TMP_ACTIVITYIsNull {
            get {
                return this.m_NO_TMP_ACTIVITYIsNull;
            }
            set {
                this.m_NO_TMP_ACTIVITYIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("SITE")]
        public string SITE {
            get {
                return this.m_SITE;
            }
            set {
                this.m_SITE = value;
            }
        }
        
        [OracleObjectMappingAttribute("STATION")]
        public string STATION {
            get {
                return this.m_STATION;
            }
            set {
                this.m_STATION = value;
            }
        }
        
        [OracleObjectMappingAttribute("CLOCKID")]
        public float CLOCKID {
            get {
                return this.m_CLOCKID;
            }
            set {
                this.m_CLOCKID = value;
                this.m_CLOCKIDIsNull = false;
            }
        }
        
        public bool CLOCKIDIsNull {
            get {
                return this.m_CLOCKIDIsNull;
            }
            set {
                this.m_CLOCKIDIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MEAL_SUPP")]
        public float MEAL_SUPP {
            get {
                return this.m_MEAL_SUPP;
            }
            set {
                this.m_MEAL_SUPP = value;
                this.m_MEAL_SUPPIsNull = false;
            }
        }
        
        public bool MEAL_SUPPIsNull {
            get {
                return this.m_MEAL_SUPPIsNull;
            }
            set {
                this.m_MEAL_SUPPIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MAKOR")]
        public string MAKOR {
            get {
                return this.m_MAKOR;
            }
            set {
                this.m_MAKOR = value;
            }
        }
        
        [OracleObjectMappingAttribute("AUTHORIZED")]
        public float AUTHORIZED {
            get {
                return this.m_AUTHORIZED;
            }
            set {
                this.m_AUTHORIZED = value;
                this.m_AUTHORIZEDIsNull = false;
            }
        }
        
        public bool AUTHORIZEDIsNull {
            get {
                return this.m_AUTHORIZEDIsNull;
            }
            set {
                this.m_AUTHORIZEDIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MACHINE")]
        public string MACHINE {
            get {
                return this.m_MACHINE;
            }
            set {
                this.m_MACHINE = value;
            }
        }
        
        [OracleObjectMappingAttribute("EXCEP")]
        public string EXCEP {
            get {
                return this.m_EXCEP;
            }
            set {
                this.m_EXCEP = value;
            }
        }
        
        [OracleObjectMappingAttribute("TAARICH")]
        public System.DateTime TAARICH {
            get {
                return this.m_TAARICH;
            }
            set {
                this.m_TAARICH = value;
                this.m_TAARICHIsNull = false;
            }
        }
        
        public bool TAARICHIsNull {
            get {
                return this.m_TAARICHIsNull;
            }
            set {
                this.m_TAARICHIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("TRAILER_BADGE")]
        public string TRAILER_BADGE {
            get {
                return this.m_TRAILER_BADGE;
            }
            set {
                this.m_TRAILER_BADGE = value;
            }
        }
        
        [OracleObjectMappingAttribute("GOOD")]
        public float GOOD {
            get {
                return this.m_GOOD;
            }
            set {
                this.m_GOOD = value;
                this.m_GOODIsNull = false;
            }
        }
        
        public bool GOODIsNull {
            get {
                return this.m_GOODIsNull;
            }
            set {
                this.m_GOODIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("PARAM2")]
        public string PARAM2 {
            get {
                return this.m_PARAM2;
            }
            set {
                this.m_PARAM2 = value;
            }
        }
        
        [OracleObjectMappingAttribute("MEAL_QUANT")]
        public float MEAL_QUANT {
            get {
                return this.m_MEAL_QUANT;
            }
            set {
                this.m_MEAL_QUANT = value;
                this.m_MEAL_QUANTIsNull = false;
            }
        }
        
        public bool MEAL_QUANTIsNull {
            get {
                return this.m_MEAL_QUANTIsNull;
            }
            set {
                this.m_MEAL_QUANTIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("OPER")]
        public string OPER {
            get {
                return this.m_OPER;
            }
            set {
                this.m_OPER = value;
            }
        }
        
        [OracleObjectMappingAttribute("TRAILER_NO")]
        public string TRAILER_NO {
            get {
                return this.m_TRAILER_NO;
            }
            set {
                this.m_TRAILER_NO = value;
            }
        }
        
        [OracleObjectMappingAttribute("XLEVEL")]
        public string XLEVEL {
            get {
                return this.m_XLEVEL;
            }
            set {
                this.m_XLEVEL = value;
            }
        }
        
        [OracleObjectMappingAttribute("LEVELORG")]
        public float LEVELORG {
            get {
                return this.m_LEVELORG;
            }
            set {
                this.m_LEVELORG = value;
                this.m_LEVELORGIsNull = false;
            }
        }
        
        public bool LEVELORGIsNull {
            get {
                return this.m_LEVELORGIsNull;
            }
            set {
                this.m_LEVELORGIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("FROM_DLL")]
        public float FROM_DLL {
            get {
                return this.m_FROM_DLL;
            }
            set {
                this.m_FROM_DLL = value;
                this.m_FROM_DLLIsNull = false;
            }
        }
        
        public bool FROM_DLLIsNull {
            get {
                return this.m_FROM_DLLIsNull;
            }
            set {
                this.m_FROM_DLLIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("PARAM1")]
        public string PARAM1 {
            get {
                return this.m_PARAM1;
            }
            set {
                this.m_PARAM1 = value;
            }
        }
        
        [OracleObjectMappingAttribute("GOOD_REC")]
        public float GOOD_REC {
            get {
                return this.m_GOOD_REC;
            }
            set {
                this.m_GOOD_REC = value;
                this.m_GOOD_RECIsNull = false;
            }
        }
        
        public bool GOOD_RECIsNull {
            get {
                return this.m_GOOD_RECIsNull;
            }
            set {
                this.m_GOOD_RECIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("PRODUCT")]
        public string PRODUCT {
            get {
                return this.m_PRODUCT;
            }
            set {
                this.m_PRODUCT = value;
            }
        }
        
        [OracleObjectMappingAttribute("PARAM4")]
        public string PARAM4 {
            get {
                return this.m_PARAM4;
            }
            set {
                this.m_PARAM4 = value;
            }
        }
        
        [OracleObjectMappingAttribute("EXECUTED")]
        public string EXECUTED {
            get {
                return this.m_EXECUTED;
            }
            set {
                this.m_EXECUTED = value;
            }
        }
        
        [OracleObjectMappingAttribute("BADGE_TYPE")]
        public float BADGE_TYPE {
            get {
                return this.m_BADGE_TYPE;
            }
            set {
                this.m_BADGE_TYPE = value;
                this.m_BADGE_TYPEIsNull = false;
            }
        }
        
        public bool BADGE_TYPEIsNull {
            get {
                return this.m_BADGE_TYPEIsNull;
            }
            set {
                this.m_BADGE_TYPEIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("TRAILER1_NO")]
        public string TRAILER1_NO {
            get {
                return this.m_TRAILER1_NO;
            }
            set {
                this.m_TRAILER1_NO = value;
            }
        }
        
        [OracleObjectMappingAttribute("STATION_W")]
        public string STATION_W {
            get {
                return this.m_STATION_W;
            }
            set {
                this.m_STATION_W = value;
            }
        }
        
        [OracleObjectMappingAttribute("HAND")]
        public float HAND {
            get {
                return this.m_HAND;
            }
            set {
                this.m_HAND = value;
                this.m_HANDIsNull = false;
            }
        }
        
        public bool HANDIsNull {
            get {
                return this.m_HANDIsNull;
            }
            set {
                this.m_HANDIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("BADGE")]
        public string BADGE {
            get {
                return this.m_BADGE;
            }
            set {
                this.m_BADGE = value;
            }
        }
        
        [OracleObjectMappingAttribute("EXPORT_P")]
        public float EXPORT_P {
            get {
                return this.m_EXPORT_P;
            }
            set {
                this.m_EXPORT_P = value;
                this.m_EXPORT_PIsNull = false;
            }
        }
        
        public bool EXPORT_PIsNull {
            get {
                return this.m_EXPORT_PIsNull;
            }
            set {
                this.m_EXPORT_PIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("UNITPROD")]
        public string UNITPROD {
            get {
                return this.m_UNITPROD;
            }
            set {
                this.m_UNITPROD = value;
            }
        }
        
        [OracleObjectMappingAttribute("ABSCODE")]
        public string ABSCODE {
            get {
                return this.m_ABSCODE;
            }
            set {
                this.m_ABSCODE = value;
            }
        }
        
        [OracleObjectMappingAttribute("NO_ACTIVITY")]
        public float NO_ACTIVITY {
            get {
                return this.m_NO_ACTIVITY;
            }
            set {
                this.m_NO_ACTIVITY = value;
                this.m_NO_ACTIVITYIsNull = false;
            }
        }
        
        public bool NO_ACTIVITYIsNull {
            get {
                return this.m_NO_ACTIVITYIsNull;
            }
            set {
                this.m_NO_ACTIVITYIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("CODE")]
        public string CODE {
            get {
                return this.m_CODE;
            }
            set {
                this.m_CODE = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            if ((HOURIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "HOUR", this.HOUR);
            }
            if ((CHANG_RECIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CHANG_REC", this.CHANG_REC);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MARKED", this.MARKED);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PARAM3", this.PARAM3);
            if ((SHIFTIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SHIFT", this.SHIFT);
            }
            if ((TAARICH_MEADKEN_ACHARONIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TAARICH_MEADKEN_ACHARON", this.TAARICH_MEADKEN_ACHARON);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PARAM6", this.PARAM6);
            if ((MEADKEN_ACHARONIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MEADKEN_ACHARON", this.MEADKEN_ACHARON);
            }
            if ((ABSTIMEIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ABSTIME", this.ABSTIME);
            }
           
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CODEORG", this.CODEORG);
            if ((DUP_RECIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "DUP_REC", this.DUP_REC);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ACTION", this.ACTION);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PARAM5", this.PARAM5);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ALTERNATIVE", this.ALTERNATIVE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "DESCR", this.DESCR);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CAR_NO", this.CAR_NO);
            if ((CODE_ERRIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CODE_ERR", this.CODE_ERR);
            }
            if ((DATETRANSFIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "DATETRANSF", this.DATETRANSF);
            }
            if ((REC_ENTERIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "REC_ENTER", this.REC_ENTER);
            }
            if ((ZIGNOREIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ZIGNORE", this.ZIGNORE);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TRAILER1_BADGE", this.TRAILER1_BADGE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "LANCH", this.LANCH);
            if ((BEDIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "BED", this.BED);
            }
            if ((L_PRESENTIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "L_PRESENT", this.L_PRESENT);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MACHINE_W", this.MACHINE_W);
            if ((EMP_NOIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "EMP_NO", this.EMP_NO);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CAR_BADGE", this.CAR_BADGE);
            if ((ERR_MOVIDIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ERR_MOVID", this.ERR_MOVID);
            }
            if ((NO_TMP_ACTIVITYIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "NO_TMP_ACTIVITY", this.NO_TMP_ACTIVITY);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SITE", this.SITE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "STATION", this.STATION);
            if ((CLOCKIDIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CLOCKID", this.CLOCKID);
            }
            if ((MEAL_SUPPIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MEAL_SUPP", this.MEAL_SUPP);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MAKOR", this.MAKOR);
            if ((AUTHORIZEDIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "AUTHORIZED", this.AUTHORIZED);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MACHINE", this.MACHINE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "EXCEP", this.EXCEP);
            if ((TAARICHIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TAARICH", this.TAARICH);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TRAILER_BADGE", this.TRAILER_BADGE);
            if ((GOODIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "GOOD", this.GOOD);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PARAM2", this.PARAM2);
            if ((MEAL_QUANTIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MEAL_QUANT", this.MEAL_QUANT);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OPER", this.OPER);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TRAILER_NO", this.TRAILER_NO);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "XLEVEL", this.XLEVEL);
            if ((LEVELORGIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "LEVELORG", this.LEVELORG);
            }
            if ((FROM_DLLIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "FROM_DLL", this.FROM_DLL);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PARAM1", this.PARAM1);
            if ((GOOD_RECIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "GOOD_REC", this.GOOD_REC);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PRODUCT", this.PRODUCT);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "PARAM4", this.PARAM4);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "EXECUTED", this.EXECUTED);
            if ((BADGE_TYPEIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "BADGE_TYPE", this.BADGE_TYPE);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TRAILER1_NO", this.TRAILER1_NO);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "STATION_W", this.STATION_W);
            if ((HANDIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "HAND", this.HAND);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "BADGE", this.BADGE);
            if ((EXPORT_PIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "EXPORT_P", this.EXPORT_P);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "UNITPROD", this.UNITPROD);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ABSCODE", this.ABSCODE);
            if ((NO_ACTIVITYIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "NO_ACTIVITY", this.NO_ACTIVITY);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CODE", this.CODE);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.HOURIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "HOUR");
            if ((HOURIsNull == false)) {
                this.HOUR = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "HOUR")));
            }
            this.CHANG_RECIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "CHANG_REC");
            if ((CHANG_RECIsNull == false)) {
                this.CHANG_REC = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CHANG_REC")));
            }
            this.MARKED = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MARKED")));
            this.PARAM3 = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PARAM3")));
            this.SHIFTIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "SHIFT");
            if ((SHIFTIsNull == false)) {
                this.SHIFT = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SHIFT")));
            }
            this.TAARICH_MEADKEN_ACHARONIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "TAARICH_MEADKEN_ACHARON");
            if ((TAARICH_MEADKEN_ACHARONIsNull == false)) {
                this.TAARICH_MEADKEN_ACHARON = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TAARICH_MEADKEN_ACHARON")));
            }
            this.PARAM6 = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PARAM6")));
            this.MEADKEN_ACHARONIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MEADKEN_ACHARON");
            if ((MEADKEN_ACHARONIsNull == false)) {
                this.MEADKEN_ACHARON = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MEADKEN_ACHARON")));
            }
            this.ABSTIMEIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ABSTIME");
            if ((ABSTIMEIsNull == false)) {
                this.ABSTIME = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ABSTIME")));
            }
          
            this.CODEORG = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CODEORG")));
            this.DUP_RECIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "DUP_REC");
            if ((DUP_RECIsNull == false)) {
                this.DUP_REC = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "DUP_REC")));
            }
            this.ACTION = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ACTION")));
            this.PARAM5 = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PARAM5")));
            this.ALTERNATIVE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ALTERNATIVE")));
            this.DESCR = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "DESCR")));
            this.CAR_NO = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CAR_NO")));
            this.CODE_ERRIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "CODE_ERR");
            if ((CODE_ERRIsNull == false)) {
                this.CODE_ERR = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CODE_ERR")));
            }
            this.DATETRANSFIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "DATETRANSF");
            if ((DATETRANSFIsNull == false)) {
                this.DATETRANSF = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "DATETRANSF")));
            }
            this.REC_ENTERIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "REC_ENTER");
            if ((REC_ENTERIsNull == false)) {
                this.REC_ENTER = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "REC_ENTER")));
            }
            this.ZIGNOREIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ZIGNORE");
            if ((ZIGNOREIsNull == false)) {
                this.ZIGNORE = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ZIGNORE")));
            }
            this.TRAILER1_BADGE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TRAILER1_BADGE")));
            this.LANCH = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "LANCH")));
            this.BEDIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "BED");
            if ((BEDIsNull == false)) {
                this.BED = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "BED")));
            }
            this.L_PRESENTIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "L_PRESENT");
            if ((L_PRESENTIsNull == false)) {
                this.L_PRESENT = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "L_PRESENT")));
            }
            this.MACHINE_W = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MACHINE_W")));
            this.EMP_NOIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "EMP_NO");
            if ((EMP_NOIsNull == false)) {
                this.EMP_NO = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "EMP_NO")));
            }
            this.CAR_BADGE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CAR_BADGE")));
            this.ERR_MOVIDIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ERR_MOVID");
            if ((ERR_MOVIDIsNull == false)) {
                this.ERR_MOVID = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ERR_MOVID")));
            }
            this.NO_TMP_ACTIVITYIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "NO_TMP_ACTIVITY");
            if ((NO_TMP_ACTIVITYIsNull == false)) {
                this.NO_TMP_ACTIVITY = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "NO_TMP_ACTIVITY")));
            }
            this.SITE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SITE")));
            this.STATION = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "STATION")));
            this.CLOCKIDIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "CLOCKID");
            if ((CLOCKIDIsNull == false)) {
                this.CLOCKID = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CLOCKID")));
            }
            this.MEAL_SUPPIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MEAL_SUPP");
            if ((MEAL_SUPPIsNull == false)) {
                this.MEAL_SUPP = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MEAL_SUPP")));
            }
            this.MAKOR = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MAKOR")));
            this.AUTHORIZEDIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "AUTHORIZED");
            if ((AUTHORIZEDIsNull == false)) {
                this.AUTHORIZED = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "AUTHORIZED")));
            }
            this.MACHINE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MACHINE")));
            this.EXCEP = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "EXCEP")));
            this.TAARICHIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "TAARICH");
            if ((TAARICHIsNull == false)) {
                this.TAARICH = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TAARICH")));
            }
            this.TRAILER_BADGE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TRAILER_BADGE")));
            this.GOODIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "GOOD");
            if ((GOODIsNull == false)) {
                this.GOOD = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "GOOD")));
            }
            this.PARAM2 = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PARAM2")));
            this.MEAL_QUANTIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MEAL_QUANT");
            if ((MEAL_QUANTIsNull == false)) {
                this.MEAL_QUANT = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MEAL_QUANT")));
            }
            this.OPER = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OPER")));
            this.TRAILER_NO = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TRAILER_NO")));
            this.XLEVEL = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "XLEVEL")));
            this.LEVELORGIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "LEVELORG");
            if ((LEVELORGIsNull == false)) {
                this.LEVELORG = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "LEVELORG")));
            }
            this.FROM_DLLIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "FROM_DLL");
            if ((FROM_DLLIsNull == false)) {
                this.FROM_DLL = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "FROM_DLL")));
            }
            this.PARAM1 = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PARAM1")));
            this.GOOD_RECIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "GOOD_REC");
            if ((GOOD_RECIsNull == false)) {
                this.GOOD_REC = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "GOOD_REC")));
            }
            this.PRODUCT = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PRODUCT")));
            this.PARAM4 = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "PARAM4")));
            this.EXECUTED = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "EXECUTED")));
            this.BADGE_TYPEIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "BADGE_TYPE");
            if ((BADGE_TYPEIsNull == false)) {
                this.BADGE_TYPE = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "BADGE_TYPE")));
            }
            this.TRAILER1_NO = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TRAILER1_NO")));
            this.STATION_W = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "STATION_W")));
            this.HANDIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "HAND");
            if ((HANDIsNull == false)) {
                this.HAND = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "HAND")));
            }
            this.BADGE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "BADGE")));
            this.EXPORT_PIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "EXPORT_P");
            if ((EXPORT_PIsNull == false)) {
                this.EXPORT_P = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "EXPORT_P")));
            }
            this.UNITPROD = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "UNITPROD")));
            this.ABSCODE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ABSCODE")));
            this.NO_ACTIVITYIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "NO_ACTIVITY");
            if ((NO_ACTIVITYIsNull == false)) {
                this.NO_ACTIVITY = ((float)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "NO_ACTIVITY")));
            }
            this.CODE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CODE")));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static OBJ_Harmony_movment_Err_Mov Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new OBJ_Harmony_movment_Err_Mov();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.OBJ_Harmony_movment_Err_Mov")]
    public class OBJ_Harmony_movment_Err_Mov_aFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            OBJ_Harmony_movment_Err_Mov obj = new OBJ_Harmony_movment_Err_Mov();
            return obj;
        }
    }
}
