//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSCommon.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;


    public class OBJ_REPORT_PARAM : INullable, IOracleCustomType, IXmlSerializable
    {

        private bool m_IsNull;

        private string m_VALUE;

        private string m_NAME;

        public OBJ_REPORT_PARAM()
        {
            // TODO : Add code to initialise the object
        }

        public OBJ_REPORT_PARAM(string Name, string Value)
        {
            m_NAME = Name;
            m_VALUE = Value;
        }

        public virtual bool IsNull
        {
            get
            {
                return this.m_IsNull;
            }
        }

        public static OBJ_REPORT_PARAM Null
        {
            get
            {
                OBJ_REPORT_PARAM obj = new OBJ_REPORT_PARAM();
                obj.m_IsNull = true;
                return obj;
            }
        }

        [OracleObjectMappingAttribute("VALUE")]
        public string VALUE
        {
            get
            {
                return this.m_VALUE;
            }
            set
            {
                this.m_VALUE = value;
            }
        }

        [OracleObjectMappingAttribute("NAME")]
        public string NAME
        {
            get
            {
                return this.m_NAME;
            }
            set
            {
                this.m_NAME = value;
            }
        }

        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt)
        {
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "VALUE", this.VALUE);
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "NAME", this.NAME);
        }

        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt)
        {
            this.VALUE = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "VALUE")));
            this.NAME = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "NAME")));
        }

        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            // TODO : Read Serialized Xml Data
        }

        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            // TODO : Serialize object to xml data
        }

        public virtual XmlSchema GetSchema()
        {
            // TODO : Implement GetSchema
            return null;
        }

        public override string ToString()
        {
            // TODO : Return a string that represents the current object
            return "";
        }

        public static OBJ_REPORT_PARAM Parse(string str)
        {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new OBJ_REPORT_PARAM();
        }
    }

    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.OBJ_REPORT_PARAM")]
    public class OBJ_REPORT_PARAMFactory : IOracleCustomTypeFactory
    {

        public virtual IOracleCustomType CreateObject()
        {
            OBJ_REPORT_PARAM obj = new OBJ_REPORT_PARAM();
            return obj;
        }
    }
}




