//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KdsClocks.syInterfaceWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="syInterfaceWS.IMalal")]
    public interface IMalal {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message echoEnumRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#echoEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.echoEnumResponse echoEnum(KdsClocks.syInterfaceWS.echoEnumRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message echoDoubleArrayRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#echoDoubleArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.echoDoubleArrayResponse echoDoubleArray(KdsClocks.syInterfaceWS.echoDoubleArrayRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message echoMyEmployeeRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#echoMyEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.echoMyEmployeeResponse echoMyEmployee(KdsClocks.syInterfaceWS.echoMyEmployeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message echoDoubleRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#echoDouble", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.echoDoubleResponse echoDouble(KdsClocks.syInterfaceWS.echoDoubleRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message HarmonyLogInRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#HarmonyLogIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.HarmonyLogInResponse HarmonyLogIn(KdsClocks.syInterfaceWS.HarmonyLogInRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message HarmonyLogOutRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#HarmonyLogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.HarmonyLogOutResponse HarmonyLogOut(KdsClocks.syInterfaceWS.HarmonyLogOutRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message XmlUpdateEmployeeRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#XmlUpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.XmlUpdateEmployeeResponse XmlUpdateEmployee(KdsClocks.syInterfaceWS.XmlUpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message XmlDeleteEmployeeRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#XmlDeleteEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.XmlDeleteEmployeeResponse XmlDeleteEmployee(KdsClocks.syInterfaceWS.XmlDeleteEmployeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message XmlGetEmployeeDetailsRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#XmlGetEmployeeDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.XmlGetEmployeeDetailsResponse XmlGetEmployeeDetails(KdsClocks.syInterfaceWS.XmlGetEmployeeDetailsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message XmlTestRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#XmlTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.XmlTestResponse XmlTest(KdsClocks.syInterfaceWS.XmlTestRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message SQLRecordSetToXMLRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#SQLRecordSetToXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.SQLRecordSetToXMLResponse SQLRecordSetToXML(KdsClocks.syInterfaceWS.SQLRecordSetToXMLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message XmlUpdateClientRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#XmlUpdateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.XmlUpdateClientResponse XmlUpdateClient(KdsClocks.syInterfaceWS.XmlUpdateClientRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message XmlDeleteClientRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#XmlDeleteClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.XmlDeleteClientResponse XmlDeleteClient(KdsClocks.syInterfaceWS.XmlDeleteClientRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message echoXmlUpdateEmployeeRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#echoXmlUpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.echoXmlUpdateEmployeeResponse echoXmlUpdateEmployee(KdsClocks.syInterfaceWS.echoXmlUpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message SetUnsetDebuggingRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#SetUnsetDebugging", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.SetUnsetDebuggingResponse SetUnsetDebugging(KdsClocks.syInterfaceWS.SetUnsetDebuggingRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message EmpPictureAsBlobToClientRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#EmpPictureAsBlobToClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.EmpPictureAsBlobToClientResponse EmpPictureAsBlobToClient(KdsClocks.syInterfaceWS.EmpPictureAsBlobToClientRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message EmpPictureAsBlobToServiceRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#EmpPictureAsBlobToService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.EmpPictureAsBlobToServiceResponse EmpPictureAsBlobToService(KdsClocks.syInterfaceWS.EmpPictureAsBlobToServiceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message EmpPictureAsFileToServiceRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#EmpPictureAsFileToService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.EmpPictureAsFileToServiceResponse EmpPictureAsFileToService(KdsClocks.syInterfaceWS.EmpPictureAsFileToServiceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message WSImportEmpBufferRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#WSImportEmpBuffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.WSImportEmpBufferResponse WSImportEmpBuffer(KdsClocks.syInterfaceWS.WSImportEmpBufferRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message WSRunCommandLineRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#WSRunCommandLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.WSRunCommandLineResponse WSRunCommandLine(KdsClocks.syInterfaceWS.WSRunCommandLineRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MalalIntf-IMalal) of message TEVAOpenCATicketRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MalalIntf-IMalal#TEVAOpenCATicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KdsClocks.syInterfaceWS.TEVAOpenCATicketResponse TEVAOpenCATicket(KdsClocks.syInterfaceWS.TEVAOpenCATicketRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MalalIntf")]
    public enum TEnumTest {
        
        /// <remarks/>
        etNone,
        
        /// <remarks/>
        etAFew,
        
        /// <remarks/>
        etSome,
        
        /// <remarks/>
        etAlot,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoEnum", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoEnumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public KdsClocks.syInterfaceWS.TEnumTest Value;
        
        public echoEnumRequest() {
        }
        
        public echoEnumRequest(KdsClocks.syInterfaceWS.TEnumTest Value) {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoEnumResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoEnumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public KdsClocks.syInterfaceWS.TEnumTest @return;
        
        public echoEnumResponse() {
        }
        
        public echoEnumResponse(KdsClocks.syInterfaceWS.TEnumTest @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDoubleArray", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoDoubleArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double[] Value;
        
        public echoDoubleArrayRequest() {
        }
        
        public echoDoubleArrayRequest(double[] Value) {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDoubleArrayResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoDoubleArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double[] @return;
        
        public echoDoubleArrayResponse() {
        }
        
        public echoDoubleArrayResponse(double[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MalalIntf")]
    public partial class TMyEmployee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lastNameField;
        
        private string firstNameField;
        
        private double salaryField;
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        public double Salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
                this.RaisePropertyChanged("Salary");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MalalIntf")]
    public partial class THarmonyEmp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double noField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime dateStartField;
        
        private System.DateTime dateEndField;
        
        private string groupCodeField;
        
        private string groupDescrField;
        
        private int eClassField;
        
        private double authortypeField;
        
        private string passportNoField;
        
        private int rateProcentField;
        
        private string nickNameField;
        
        private double dailyTransportField;
        
        private double fixTransportField;
        
        private string payrollIDField;
        
        private System.DateTime emmigrationDateField;
        
        private int jobCodeField;
        
        private string jobDescrField;
        
        private int meritalCodeField;
        
        private string meritalDescrField;
        
        private bool activeField;
        
        private string stationCodeField;
        
        private string stationDescrField;
        
        private string departmentCodeField;
        
        private string departmentDescrField;
        
        private string sectionCodeField;
        
        private string sectionDescrField;
        
        private string factoryCodeField;
        
        private string factoryDescrField;
        
        private string regionCodeField;
        
        private string regionDescrField;
        
        private string tagField;
        
        private System.DateTime tagStartDateField;
        
        private System.DateTime tagEndDateField;
        
        private int tagTypeField;
        
        private int tagStatusField;
        
        private int tagResonField;
        
        private string tagResonDescrField;
        
        private int tagTypeCreatedField;
        
        private string tagVersionField;
        
        private int sGCodeField;
        
        private string sGDescrField;
        
        private int sG2LevelOrgField;
        
        private string sG2CodeOrgField;
        
        private System.DateTime sGDateFromField;
        
        private System.DateTime sGDateToField;
        
        private bool enrollField;
        
        private bool fPUField;
        
        private string picField;
        
        private int empTypeField;
        
        private string clndTypeField;
        
        private int patternNoField;
        
        private int mealTypeField;
        
        private int cardTemplateDefaultField;
        
        private System.DateTime safetyTrainingDateField;
        
        private string assignToPointField;
        
        private string contactCodeListField;
        
        private string contactNumberListField;
        
        private string carNoField;
        
        private int carTypeField;
        
        private int companyIdField;
        
        private string companyDescrField;
        
        /// <remarks/>
        public double No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        public System.DateTime DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
                this.RaisePropertyChanged("DateStart");
            }
        }
        
        /// <remarks/>
        public System.DateTime DateEnd {
            get {
                return this.dateEndField;
            }
            set {
                this.dateEndField = value;
                this.RaisePropertyChanged("DateEnd");
            }
        }
        
        /// <remarks/>
        public string GroupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
                this.RaisePropertyChanged("GroupCode");
            }
        }
        
        /// <remarks/>
        public string GroupDescr {
            get {
                return this.groupDescrField;
            }
            set {
                this.groupDescrField = value;
                this.RaisePropertyChanged("GroupDescr");
            }
        }
        
        /// <remarks/>
        public int EClass {
            get {
                return this.eClassField;
            }
            set {
                this.eClassField = value;
                this.RaisePropertyChanged("EClass");
            }
        }
        
        /// <remarks/>
        public double Authortype {
            get {
                return this.authortypeField;
            }
            set {
                this.authortypeField = value;
                this.RaisePropertyChanged("Authortype");
            }
        }
        
        /// <remarks/>
        public string PassportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
                this.RaisePropertyChanged("PassportNo");
            }
        }
        
        /// <remarks/>
        public int RateProcent {
            get {
                return this.rateProcentField;
            }
            set {
                this.rateProcentField = value;
                this.RaisePropertyChanged("RateProcent");
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
                this.RaisePropertyChanged("NickName");
            }
        }
        
        /// <remarks/>
        public double DailyTransport {
            get {
                return this.dailyTransportField;
            }
            set {
                this.dailyTransportField = value;
                this.RaisePropertyChanged("DailyTransport");
            }
        }
        
        /// <remarks/>
        public double FixTransport {
            get {
                return this.fixTransportField;
            }
            set {
                this.fixTransportField = value;
                this.RaisePropertyChanged("FixTransport");
            }
        }
        
        /// <remarks/>
        public string PayrollID {
            get {
                return this.payrollIDField;
            }
            set {
                this.payrollIDField = value;
                this.RaisePropertyChanged("PayrollID");
            }
        }
        
        /// <remarks/>
        public System.DateTime EmmigrationDate {
            get {
                return this.emmigrationDateField;
            }
            set {
                this.emmigrationDateField = value;
                this.RaisePropertyChanged("EmmigrationDate");
            }
        }
        
        /// <remarks/>
        public int JobCode {
            get {
                return this.jobCodeField;
            }
            set {
                this.jobCodeField = value;
                this.RaisePropertyChanged("JobCode");
            }
        }
        
        /// <remarks/>
        public string JobDescr {
            get {
                return this.jobDescrField;
            }
            set {
                this.jobDescrField = value;
                this.RaisePropertyChanged("JobDescr");
            }
        }
        
        /// <remarks/>
        public int MeritalCode {
            get {
                return this.meritalCodeField;
            }
            set {
                this.meritalCodeField = value;
                this.RaisePropertyChanged("MeritalCode");
            }
        }
        
        /// <remarks/>
        public string MeritalDescr {
            get {
                return this.meritalDescrField;
            }
            set {
                this.meritalDescrField = value;
                this.RaisePropertyChanged("MeritalDescr");
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        public string StationCode {
            get {
                return this.stationCodeField;
            }
            set {
                this.stationCodeField = value;
                this.RaisePropertyChanged("StationCode");
            }
        }
        
        /// <remarks/>
        public string StationDescr {
            get {
                return this.stationDescrField;
            }
            set {
                this.stationDescrField = value;
                this.RaisePropertyChanged("StationDescr");
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
                this.RaisePropertyChanged("DepartmentCode");
            }
        }
        
        /// <remarks/>
        public string DepartmentDescr {
            get {
                return this.departmentDescrField;
            }
            set {
                this.departmentDescrField = value;
                this.RaisePropertyChanged("DepartmentDescr");
            }
        }
        
        /// <remarks/>
        public string SectionCode {
            get {
                return this.sectionCodeField;
            }
            set {
                this.sectionCodeField = value;
                this.RaisePropertyChanged("SectionCode");
            }
        }
        
        /// <remarks/>
        public string SectionDescr {
            get {
                return this.sectionDescrField;
            }
            set {
                this.sectionDescrField = value;
                this.RaisePropertyChanged("SectionDescr");
            }
        }
        
        /// <remarks/>
        public string FactoryCode {
            get {
                return this.factoryCodeField;
            }
            set {
                this.factoryCodeField = value;
                this.RaisePropertyChanged("FactoryCode");
            }
        }
        
        /// <remarks/>
        public string FactoryDescr {
            get {
                return this.factoryDescrField;
            }
            set {
                this.factoryDescrField = value;
                this.RaisePropertyChanged("FactoryDescr");
            }
        }
        
        /// <remarks/>
        public string RegionCode {
            get {
                return this.regionCodeField;
            }
            set {
                this.regionCodeField = value;
                this.RaisePropertyChanged("RegionCode");
            }
        }
        
        /// <remarks/>
        public string RegionDescr {
            get {
                return this.regionDescrField;
            }
            set {
                this.regionDescrField = value;
                this.RaisePropertyChanged("RegionDescr");
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        public System.DateTime TagStartDate {
            get {
                return this.tagStartDateField;
            }
            set {
                this.tagStartDateField = value;
                this.RaisePropertyChanged("TagStartDate");
            }
        }
        
        /// <remarks/>
        public System.DateTime TagEndDate {
            get {
                return this.tagEndDateField;
            }
            set {
                this.tagEndDateField = value;
                this.RaisePropertyChanged("TagEndDate");
            }
        }
        
        /// <remarks/>
        public int TagType {
            get {
                return this.tagTypeField;
            }
            set {
                this.tagTypeField = value;
                this.RaisePropertyChanged("TagType");
            }
        }
        
        /// <remarks/>
        public int TagStatus {
            get {
                return this.tagStatusField;
            }
            set {
                this.tagStatusField = value;
                this.RaisePropertyChanged("TagStatus");
            }
        }
        
        /// <remarks/>
        public int TagReson {
            get {
                return this.tagResonField;
            }
            set {
                this.tagResonField = value;
                this.RaisePropertyChanged("TagReson");
            }
        }
        
        /// <remarks/>
        public string TagResonDescr {
            get {
                return this.tagResonDescrField;
            }
            set {
                this.tagResonDescrField = value;
                this.RaisePropertyChanged("TagResonDescr");
            }
        }
        
        /// <remarks/>
        public int TagTypeCreated {
            get {
                return this.tagTypeCreatedField;
            }
            set {
                this.tagTypeCreatedField = value;
                this.RaisePropertyChanged("TagTypeCreated");
            }
        }
        
        /// <remarks/>
        public string TagVersion {
            get {
                return this.tagVersionField;
            }
            set {
                this.tagVersionField = value;
                this.RaisePropertyChanged("TagVersion");
            }
        }
        
        /// <remarks/>
        public int SGCode {
            get {
                return this.sGCodeField;
            }
            set {
                this.sGCodeField = value;
                this.RaisePropertyChanged("SGCode");
            }
        }
        
        /// <remarks/>
        public string SGDescr {
            get {
                return this.sGDescrField;
            }
            set {
                this.sGDescrField = value;
                this.RaisePropertyChanged("SGDescr");
            }
        }
        
        /// <remarks/>
        public int SG2LevelOrg {
            get {
                return this.sG2LevelOrgField;
            }
            set {
                this.sG2LevelOrgField = value;
                this.RaisePropertyChanged("SG2LevelOrg");
            }
        }
        
        /// <remarks/>
        public string SG2CodeOrg {
            get {
                return this.sG2CodeOrgField;
            }
            set {
                this.sG2CodeOrgField = value;
                this.RaisePropertyChanged("SG2CodeOrg");
            }
        }
        
        /// <remarks/>
        public System.DateTime SGDateFrom {
            get {
                return this.sGDateFromField;
            }
            set {
                this.sGDateFromField = value;
                this.RaisePropertyChanged("SGDateFrom");
            }
        }
        
        /// <remarks/>
        public System.DateTime SGDateTo {
            get {
                return this.sGDateToField;
            }
            set {
                this.sGDateToField = value;
                this.RaisePropertyChanged("SGDateTo");
            }
        }
        
        /// <remarks/>
        public bool Enroll {
            get {
                return this.enrollField;
            }
            set {
                this.enrollField = value;
                this.RaisePropertyChanged("Enroll");
            }
        }
        
        /// <remarks/>
        public bool FPU {
            get {
                return this.fPUField;
            }
            set {
                this.fPUField = value;
                this.RaisePropertyChanged("FPU");
            }
        }
        
        /// <remarks/>
        public string Pic {
            get {
                return this.picField;
            }
            set {
                this.picField = value;
                this.RaisePropertyChanged("Pic");
            }
        }
        
        /// <remarks/>
        public int EmpType {
            get {
                return this.empTypeField;
            }
            set {
                this.empTypeField = value;
                this.RaisePropertyChanged("EmpType");
            }
        }
        
        /// <remarks/>
        public string ClndType {
            get {
                return this.clndTypeField;
            }
            set {
                this.clndTypeField = value;
                this.RaisePropertyChanged("ClndType");
            }
        }
        
        /// <remarks/>
        public int PatternNo {
            get {
                return this.patternNoField;
            }
            set {
                this.patternNoField = value;
                this.RaisePropertyChanged("PatternNo");
            }
        }
        
        /// <remarks/>
        public int MealType {
            get {
                return this.mealTypeField;
            }
            set {
                this.mealTypeField = value;
                this.RaisePropertyChanged("MealType");
            }
        }
        
        /// <remarks/>
        public int CardTemplateDefault {
            get {
                return this.cardTemplateDefaultField;
            }
            set {
                this.cardTemplateDefaultField = value;
                this.RaisePropertyChanged("CardTemplateDefault");
            }
        }
        
        /// <remarks/>
        public System.DateTime SafetyTrainingDate {
            get {
                return this.safetyTrainingDateField;
            }
            set {
                this.safetyTrainingDateField = value;
                this.RaisePropertyChanged("SafetyTrainingDate");
            }
        }
        
        /// <remarks/>
        public string AssignToPoint {
            get {
                return this.assignToPointField;
            }
            set {
                this.assignToPointField = value;
                this.RaisePropertyChanged("AssignToPoint");
            }
        }
        
        /// <remarks/>
        public string ContactCodeList {
            get {
                return this.contactCodeListField;
            }
            set {
                this.contactCodeListField = value;
                this.RaisePropertyChanged("ContactCodeList");
            }
        }
        
        /// <remarks/>
        public string ContactNumberList {
            get {
                return this.contactNumberListField;
            }
            set {
                this.contactNumberListField = value;
                this.RaisePropertyChanged("ContactNumberList");
            }
        }
        
        /// <remarks/>
        public string CarNo {
            get {
                return this.carNoField;
            }
            set {
                this.carNoField = value;
                this.RaisePropertyChanged("CarNo");
            }
        }
        
        /// <remarks/>
        public int CarType {
            get {
                return this.carTypeField;
            }
            set {
                this.carTypeField = value;
                this.RaisePropertyChanged("CarType");
            }
        }
        
        /// <remarks/>
        public int CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("CompanyId");
            }
        }
        
        /// <remarks/>
        public string CompanyDescr {
            get {
                return this.companyDescrField;
            }
            set {
                this.companyDescrField = value;
                this.RaisePropertyChanged("CompanyDescr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoMyEmployee", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoMyEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public KdsClocks.syInterfaceWS.TMyEmployee Value;
        
        public echoMyEmployeeRequest() {
        }
        
        public echoMyEmployeeRequest(KdsClocks.syInterfaceWS.TMyEmployee Value) {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoMyEmployeeResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoMyEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public KdsClocks.syInterfaceWS.TMyEmployee @return;
        
        public echoMyEmployeeResponse() {
        }
        
        public echoMyEmployeeResponse(KdsClocks.syInterfaceWS.TMyEmployee @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDouble", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoDoubleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double Value;
        
        public echoDoubleRequest() {
        }
        
        public echoDoubleRequest(double Value) {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoDoubleResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoDoubleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public echoDoubleResponse() {
        }
        
        public echoDoubleResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HarmonyLogIn", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class HarmonyLogInRequest {
        
        public HarmonyLogInRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HarmonyLogInResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class HarmonyLogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public HarmonyLogInResponse() {
        }
        
        public HarmonyLogInResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HarmonyLogOut", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class HarmonyLogOutRequest {
        
        public HarmonyLogOutRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HarmonyLogOutResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class HarmonyLogOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public HarmonyLogOutResponse() {
        }
        
        public HarmonyLogOutResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlUpdateEmployee", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlUpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string einXML;
        
        public XmlUpdateEmployeeRequest() {
        }
        
        public XmlUpdateEmployeeRequest(string einXML) {
            this.einXML = einXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlUpdateEmployeeResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlUpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public XmlUpdateEmployeeResponse() {
        }
        
        public XmlUpdateEmployeeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlDeleteEmployee", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlDeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string einXML;
        
        public XmlDeleteEmployeeRequest() {
        }
        
        public XmlDeleteEmployeeRequest(string einXML) {
            this.einXML = einXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlDeleteEmployeeResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlDeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public XmlDeleteEmployeeResponse() {
        }
        
        public XmlDeleteEmployeeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlGetEmployeeDetails", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlGetEmployeeDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string einXML;
        
        public XmlGetEmployeeDetailsRequest() {
        }
        
        public XmlGetEmployeeDetailsRequest(string einXML) {
            this.einXML = einXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlGetEmployeeDetailsResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlGetEmployeeDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public XmlGetEmployeeDetailsResponse() {
        }
        
        public XmlGetEmployeeDetailsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlTest", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string einXML;
        
        public XmlTestRequest() {
        }
        
        public XmlTestRequest(string einXML) {
            this.einXML = einXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlTestResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public XmlTestResponse() {
        }
        
        public XmlTestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SQLRecordSetToXML", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class SQLRecordSetToXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        public SQLRecordSetToXMLRequest() {
        }
        
        public SQLRecordSetToXMLRequest(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SQLRecordSetToXMLResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class SQLRecordSetToXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SQLRecordSetToXMLResponse() {
        }
        
        public SQLRecordSetToXMLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlUpdateClient", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlUpdateClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string einXML;
        
        public XmlUpdateClientRequest() {
        }
        
        public XmlUpdateClientRequest(string einXML) {
            this.einXML = einXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlUpdateClientResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlUpdateClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public XmlUpdateClientResponse() {
        }
        
        public XmlUpdateClientResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlDeleteClient", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlDeleteClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string einXML;
        
        public XmlDeleteClientRequest() {
        }
        
        public XmlDeleteClientRequest(string einXML) {
            this.einXML = einXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XmlDeleteClientResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class XmlDeleteClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public XmlDeleteClientResponse() {
        }
        
        public XmlDeleteClientResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoXmlUpdateEmployee", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoXmlUpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public KdsClocks.syInterfaceWS.THarmonyEmp Value;
        
        public echoXmlUpdateEmployeeRequest() {
        }
        
        public echoXmlUpdateEmployeeRequest(KdsClocks.syInterfaceWS.THarmonyEmp Value) {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoXmlUpdateEmployeeResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class echoXmlUpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public echoXmlUpdateEmployeeResponse() {
        }
        
        public echoXmlUpdateEmployeeResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUnsetDebugging", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class SetUnsetDebuggingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool xValue;
        
        public SetUnsetDebuggingRequest() {
        }
        
        public SetUnsetDebuggingRequest(bool xValue) {
            this.xValue = xValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUnsetDebuggingResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class SetUnsetDebuggingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SetUnsetDebuggingResponse() {
        }
        
        public SetUnsetDebuggingResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpPictureAsBlobToClient", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class EmpPictureAsBlobToClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        public EmpPictureAsBlobToClientRequest() {
        }
        
        public EmpPictureAsBlobToClientRequest(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpPictureAsBlobToClientResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class EmpPictureAsBlobToClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public EmpPictureAsBlobToClientResponse() {
        }
        
        public EmpPictureAsBlobToClientResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpPictureAsBlobToService", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class EmpPictureAsBlobToServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xEmpNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xBlobSTR;
        
        public EmpPictureAsBlobToServiceRequest() {
        }
        
        public EmpPictureAsBlobToServiceRequest(string xEmpNo, string xBlobSTR) {
            this.xEmpNo = xEmpNo;
            this.xBlobSTR = xBlobSTR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpPictureAsBlobToServiceResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class EmpPictureAsBlobToServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public EmpPictureAsBlobToServiceResponse() {
        }
        
        public EmpPictureAsBlobToServiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpPictureAsFileToService", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class EmpPictureAsFileToServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xEmp_No;
        
        public EmpPictureAsFileToServiceRequest() {
        }
        
        public EmpPictureAsFileToServiceRequest(string xFileName, string xEmp_No) {
            this.xFileName = xFileName;
            this.xEmp_No = xEmp_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpPictureAsFileToServiceResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class EmpPictureAsFileToServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public EmpPictureAsFileToServiceResponse() {
        }
        
        public EmpPictureAsFileToServiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSImportEmpBuffer", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class WSImportEmpBufferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte forceRollBack;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double EmpNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string strParam;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int intParam;
        
        public WSImportEmpBufferRequest() {
        }
        
        public WSImportEmpBufferRequest(byte forceRollBack, double EmpNo, string strParam, int intParam) {
            this.forceRollBack = forceRollBack;
            this.EmpNo = EmpNo;
            this.strParam = strParam;
            this.intParam = intParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSImportEmpBufferResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class WSImportEmpBufferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public WSImportEmpBufferResponse() {
        }
        
        public WSImportEmpBufferResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSRunCommandLine", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class WSRunCommandLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int exeCmdType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string exeProg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string @params;
        
        public WSRunCommandLineRequest() {
        }
        
        public WSRunCommandLineRequest(int exeCmdType, string exeProg, string @params) {
            this.exeCmdType = exeCmdType;
            this.exeProg = exeProg;
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSRunCommandLineResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class WSRunCommandLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public WSRunCommandLineResponse() {
        }
        
        public WSRunCommandLineResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TEVAOpenCATicket", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class TEVAOpenCATicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TicketINIType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CATicketErrMsg;
        
        public TEVAOpenCATicketRequest() {
        }
        
        public TEVAOpenCATicketRequest(string TicketINIType, string CATicketErrMsg) {
            this.TicketINIType = TicketINIType;
            this.CATicketErrMsg = CATicketErrMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TEVAOpenCATicketResponse", WrapperNamespace="urn:MalalIntf-IMalal", IsWrapped=true)]
    public partial class TEVAOpenCATicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public TEVAOpenCATicketResponse() {
        }
        
        public TEVAOpenCATicketResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMalalChannel : KdsClocks.syInterfaceWS.IMalal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MalalClient : System.ServiceModel.ClientBase<KdsClocks.syInterfaceWS.IMalal>, KdsClocks.syInterfaceWS.IMalal {
        
        public MalalClient() {
        }
        
        public MalalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MalalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MalalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MalalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.echoEnumResponse KdsClocks.syInterfaceWS.IMalal.echoEnum(KdsClocks.syInterfaceWS.echoEnumRequest request) {
            return base.Channel.echoEnum(request);
        }
        
        public KdsClocks.syInterfaceWS.TEnumTest echoEnum(KdsClocks.syInterfaceWS.TEnumTest Value) {
            KdsClocks.syInterfaceWS.echoEnumRequest inValue = new KdsClocks.syInterfaceWS.echoEnumRequest();
            inValue.Value = Value;
            KdsClocks.syInterfaceWS.echoEnumResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).echoEnum(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.echoDoubleArrayResponse KdsClocks.syInterfaceWS.IMalal.echoDoubleArray(KdsClocks.syInterfaceWS.echoDoubleArrayRequest request) {
            return base.Channel.echoDoubleArray(request);
        }
        
        public double[] echoDoubleArray(double[] Value) {
            KdsClocks.syInterfaceWS.echoDoubleArrayRequest inValue = new KdsClocks.syInterfaceWS.echoDoubleArrayRequest();
            inValue.Value = Value;
            KdsClocks.syInterfaceWS.echoDoubleArrayResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).echoDoubleArray(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.echoMyEmployeeResponse KdsClocks.syInterfaceWS.IMalal.echoMyEmployee(KdsClocks.syInterfaceWS.echoMyEmployeeRequest request) {
            return base.Channel.echoMyEmployee(request);
        }
        
        public KdsClocks.syInterfaceWS.TMyEmployee echoMyEmployee(KdsClocks.syInterfaceWS.TMyEmployee Value) {
            KdsClocks.syInterfaceWS.echoMyEmployeeRequest inValue = new KdsClocks.syInterfaceWS.echoMyEmployeeRequest();
            inValue.Value = Value;
            KdsClocks.syInterfaceWS.echoMyEmployeeResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).echoMyEmployee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.echoDoubleResponse KdsClocks.syInterfaceWS.IMalal.echoDouble(KdsClocks.syInterfaceWS.echoDoubleRequest request) {
            return base.Channel.echoDouble(request);
        }
        
        public double echoDouble(double Value) {
            KdsClocks.syInterfaceWS.echoDoubleRequest inValue = new KdsClocks.syInterfaceWS.echoDoubleRequest();
            inValue.Value = Value;
            KdsClocks.syInterfaceWS.echoDoubleResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).echoDouble(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.HarmonyLogInResponse KdsClocks.syInterfaceWS.IMalal.HarmonyLogIn(KdsClocks.syInterfaceWS.HarmonyLogInRequest request) {
            return base.Channel.HarmonyLogIn(request);
        }
        
        public string HarmonyLogIn() {
            KdsClocks.syInterfaceWS.HarmonyLogInRequest inValue = new KdsClocks.syInterfaceWS.HarmonyLogInRequest();
            KdsClocks.syInterfaceWS.HarmonyLogInResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).HarmonyLogIn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.HarmonyLogOutResponse KdsClocks.syInterfaceWS.IMalal.HarmonyLogOut(KdsClocks.syInterfaceWS.HarmonyLogOutRequest request) {
            return base.Channel.HarmonyLogOut(request);
        }
        
        public string HarmonyLogOut() {
            KdsClocks.syInterfaceWS.HarmonyLogOutRequest inValue = new KdsClocks.syInterfaceWS.HarmonyLogOutRequest();
            KdsClocks.syInterfaceWS.HarmonyLogOutResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).HarmonyLogOut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.XmlUpdateEmployeeResponse KdsClocks.syInterfaceWS.IMalal.XmlUpdateEmployee(KdsClocks.syInterfaceWS.XmlUpdateEmployeeRequest request) {
            return base.Channel.XmlUpdateEmployee(request);
        }
        
        public string XmlUpdateEmployee(string einXML) {
            KdsClocks.syInterfaceWS.XmlUpdateEmployeeRequest inValue = new KdsClocks.syInterfaceWS.XmlUpdateEmployeeRequest();
            inValue.einXML = einXML;
            KdsClocks.syInterfaceWS.XmlUpdateEmployeeResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).XmlUpdateEmployee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.XmlDeleteEmployeeResponse KdsClocks.syInterfaceWS.IMalal.XmlDeleteEmployee(KdsClocks.syInterfaceWS.XmlDeleteEmployeeRequest request) {
            return base.Channel.XmlDeleteEmployee(request);
        }
        
        public string XmlDeleteEmployee(string einXML) {
            KdsClocks.syInterfaceWS.XmlDeleteEmployeeRequest inValue = new KdsClocks.syInterfaceWS.XmlDeleteEmployeeRequest();
            inValue.einXML = einXML;
            KdsClocks.syInterfaceWS.XmlDeleteEmployeeResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).XmlDeleteEmployee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.XmlGetEmployeeDetailsResponse KdsClocks.syInterfaceWS.IMalal.XmlGetEmployeeDetails(KdsClocks.syInterfaceWS.XmlGetEmployeeDetailsRequest request) {
            return base.Channel.XmlGetEmployeeDetails(request);
        }
        
        public string XmlGetEmployeeDetails(string einXML) {
            KdsClocks.syInterfaceWS.XmlGetEmployeeDetailsRequest inValue = new KdsClocks.syInterfaceWS.XmlGetEmployeeDetailsRequest();
            inValue.einXML = einXML;
            KdsClocks.syInterfaceWS.XmlGetEmployeeDetailsResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).XmlGetEmployeeDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.XmlTestResponse KdsClocks.syInterfaceWS.IMalal.XmlTest(KdsClocks.syInterfaceWS.XmlTestRequest request) {
            return base.Channel.XmlTest(request);
        }
        
        public string XmlTest(string einXML) {
            KdsClocks.syInterfaceWS.XmlTestRequest inValue = new KdsClocks.syInterfaceWS.XmlTestRequest();
            inValue.einXML = einXML;
            KdsClocks.syInterfaceWS.XmlTestResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).XmlTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.SQLRecordSetToXMLResponse KdsClocks.syInterfaceWS.IMalal.SQLRecordSetToXML(KdsClocks.syInterfaceWS.SQLRecordSetToXMLRequest request) {
            return base.Channel.SQLRecordSetToXML(request);
        }
        
        public string SQLRecordSetToXML(string sql) {
            KdsClocks.syInterfaceWS.SQLRecordSetToXMLRequest inValue = new KdsClocks.syInterfaceWS.SQLRecordSetToXMLRequest();
            inValue.sql = sql;
            KdsClocks.syInterfaceWS.SQLRecordSetToXMLResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).SQLRecordSetToXML(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.XmlUpdateClientResponse KdsClocks.syInterfaceWS.IMalal.XmlUpdateClient(KdsClocks.syInterfaceWS.XmlUpdateClientRequest request) {
            return base.Channel.XmlUpdateClient(request);
        }
        
        public string XmlUpdateClient(string einXML) {
            KdsClocks.syInterfaceWS.XmlUpdateClientRequest inValue = new KdsClocks.syInterfaceWS.XmlUpdateClientRequest();
            inValue.einXML = einXML;
            KdsClocks.syInterfaceWS.XmlUpdateClientResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).XmlUpdateClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.XmlDeleteClientResponse KdsClocks.syInterfaceWS.IMalal.XmlDeleteClient(KdsClocks.syInterfaceWS.XmlDeleteClientRequest request) {
            return base.Channel.XmlDeleteClient(request);
        }
        
        public string XmlDeleteClient(string einXML) {
            KdsClocks.syInterfaceWS.XmlDeleteClientRequest inValue = new KdsClocks.syInterfaceWS.XmlDeleteClientRequest();
            inValue.einXML = einXML;
            KdsClocks.syInterfaceWS.XmlDeleteClientResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).XmlDeleteClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.echoXmlUpdateEmployeeResponse KdsClocks.syInterfaceWS.IMalal.echoXmlUpdateEmployee(KdsClocks.syInterfaceWS.echoXmlUpdateEmployeeRequest request) {
            return base.Channel.echoXmlUpdateEmployee(request);
        }
        
        public bool echoXmlUpdateEmployee(KdsClocks.syInterfaceWS.THarmonyEmp Value) {
            KdsClocks.syInterfaceWS.echoXmlUpdateEmployeeRequest inValue = new KdsClocks.syInterfaceWS.echoXmlUpdateEmployeeRequest();
            inValue.Value = Value;
            KdsClocks.syInterfaceWS.echoXmlUpdateEmployeeResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).echoXmlUpdateEmployee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.SetUnsetDebuggingResponse KdsClocks.syInterfaceWS.IMalal.SetUnsetDebugging(KdsClocks.syInterfaceWS.SetUnsetDebuggingRequest request) {
            return base.Channel.SetUnsetDebugging(request);
        }
        
        public string SetUnsetDebugging(bool xValue) {
            KdsClocks.syInterfaceWS.SetUnsetDebuggingRequest inValue = new KdsClocks.syInterfaceWS.SetUnsetDebuggingRequest();
            inValue.xValue = xValue;
            KdsClocks.syInterfaceWS.SetUnsetDebuggingResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).SetUnsetDebugging(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.EmpPictureAsBlobToClientResponse KdsClocks.syInterfaceWS.IMalal.EmpPictureAsBlobToClient(KdsClocks.syInterfaceWS.EmpPictureAsBlobToClientRequest request) {
            return base.Channel.EmpPictureAsBlobToClient(request);
        }
        
        public byte[] EmpPictureAsBlobToClient(string sql) {
            KdsClocks.syInterfaceWS.EmpPictureAsBlobToClientRequest inValue = new KdsClocks.syInterfaceWS.EmpPictureAsBlobToClientRequest();
            inValue.sql = sql;
            KdsClocks.syInterfaceWS.EmpPictureAsBlobToClientResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).EmpPictureAsBlobToClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.EmpPictureAsBlobToServiceResponse KdsClocks.syInterfaceWS.IMalal.EmpPictureAsBlobToService(KdsClocks.syInterfaceWS.EmpPictureAsBlobToServiceRequest request) {
            return base.Channel.EmpPictureAsBlobToService(request);
        }
        
        public string EmpPictureAsBlobToService(string xEmpNo, string xBlobSTR) {
            KdsClocks.syInterfaceWS.EmpPictureAsBlobToServiceRequest inValue = new KdsClocks.syInterfaceWS.EmpPictureAsBlobToServiceRequest();
            inValue.xEmpNo = xEmpNo;
            inValue.xBlobSTR = xBlobSTR;
            KdsClocks.syInterfaceWS.EmpPictureAsBlobToServiceResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).EmpPictureAsBlobToService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.EmpPictureAsFileToServiceResponse KdsClocks.syInterfaceWS.IMalal.EmpPictureAsFileToService(KdsClocks.syInterfaceWS.EmpPictureAsFileToServiceRequest request) {
            return base.Channel.EmpPictureAsFileToService(request);
        }
        
        public string EmpPictureAsFileToService(string xFileName, string xEmp_No) {
            KdsClocks.syInterfaceWS.EmpPictureAsFileToServiceRequest inValue = new KdsClocks.syInterfaceWS.EmpPictureAsFileToServiceRequest();
            inValue.xFileName = xFileName;
            inValue.xEmp_No = xEmp_No;
            KdsClocks.syInterfaceWS.EmpPictureAsFileToServiceResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).EmpPictureAsFileToService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.WSImportEmpBufferResponse KdsClocks.syInterfaceWS.IMalal.WSImportEmpBuffer(KdsClocks.syInterfaceWS.WSImportEmpBufferRequest request) {
            return base.Channel.WSImportEmpBuffer(request);
        }
        
        public string WSImportEmpBuffer(byte forceRollBack, double EmpNo, string strParam, int intParam) {
            KdsClocks.syInterfaceWS.WSImportEmpBufferRequest inValue = new KdsClocks.syInterfaceWS.WSImportEmpBufferRequest();
            inValue.forceRollBack = forceRollBack;
            inValue.EmpNo = EmpNo;
            inValue.strParam = strParam;
            inValue.intParam = intParam;
            KdsClocks.syInterfaceWS.WSImportEmpBufferResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).WSImportEmpBuffer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.WSRunCommandLineResponse KdsClocks.syInterfaceWS.IMalal.WSRunCommandLine(KdsClocks.syInterfaceWS.WSRunCommandLineRequest request) {
            return base.Channel.WSRunCommandLine(request);
        }
        
        public string WSRunCommandLine(int exeCmdType, string exeProg, string @params) {
            KdsClocks.syInterfaceWS.WSRunCommandLineRequest inValue = new KdsClocks.syInterfaceWS.WSRunCommandLineRequest();
            inValue.exeCmdType = exeCmdType;
            inValue.exeProg = exeProg;
            inValue.@params = @params;
            KdsClocks.syInterfaceWS.WSRunCommandLineResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).WSRunCommandLine(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KdsClocks.syInterfaceWS.TEVAOpenCATicketResponse KdsClocks.syInterfaceWS.IMalal.TEVAOpenCATicket(KdsClocks.syInterfaceWS.TEVAOpenCATicketRequest request) {
            return base.Channel.TEVAOpenCATicket(request);
        }
        
        public string TEVAOpenCATicket(string TicketINIType, string CATicketErrMsg) {
            KdsClocks.syInterfaceWS.TEVAOpenCATicketRequest inValue = new KdsClocks.syInterfaceWS.TEVAOpenCATicketRequest();
            inValue.TicketINIType = TicketINIType;
            inValue.CATicketErrMsg = CATicketErrMsg;
            KdsClocks.syInterfaceWS.TEVAOpenCATicketResponse retVal = ((KdsClocks.syInterfaceWS.IMalal)(this)).TEVAOpenCATicket(inValue);
            return retVal.@return;
        }
    }
}
