//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KdsLibrary.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class COLL_MEAFYENEY_OVED : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private OBJ_MEAFYENEY_OVED[] m_OBJ_MEAFYENEY_OVED;
        
        public COLL_MEAFYENEY_OVED() {
            // TODO : Add code to initialise the object
        }
        
        public COLL_MEAFYENEY_OVED(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static COLL_MEAFYENEY_OVED Null {
            get {
                COLL_MEAFYENEY_OVED obj = new COLL_MEAFYENEY_OVED();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleArrayMappingAttribute()]
        public virtual OBJ_MEAFYENEY_OVED[] Value {
            get {
                return this.m_OBJ_MEAFYENEY_OVED;
            }
            set {
                this.m_OBJ_MEAFYENEY_OVED = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            OracleUdt.SetValue(con, pUdt, 0, this.m_OBJ_MEAFYENEY_OVED);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.m_OBJ_MEAFYENEY_OVED = ((OBJ_MEAFYENEY_OVED[])(OracleUdt.GetValue(con, pUdt, 0)));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static COLL_MEAFYENEY_OVED Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new COLL_MEAFYENEY_OVED();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.COLL_MEAFYENEY_OVED")]
    public class COLL_MEAFYENEY_OVEDFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            COLL_MEAFYENEY_OVED obj = new COLL_MEAFYENEY_OVED();
            return obj;
        }
        
        public virtual System.Array CreateArray(int length) {
            OBJ_MEAFYENEY_OVED[] collElem = new OBJ_MEAFYENEY_OVED[length];
            return collElem;
        }
        
        public virtual System.Array CreateStatusArray(int length) {
            return null;
        }
    }
}
