//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSCommon.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    using KDSCommon.Helpers;
    
    public class COLL_OVDIM_IM_SHINUY_HR : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        private long _Count;
        private long _FirstEmpty ;
        private long _Size= 0 ; 
        private OBJ_OVDIM_IM_SHINUY_HR[] m_OBJ_OVDIM_IM_SHINUY_HR;
  
        
        public COLL_OVDIM_IM_SHINUY_HR() {
            m_IsNull = false;
            _FirstEmpty = 0; 
            // TODO : Add code to initialise the object
        }
        public COLL_OVDIM_IM_SHINUY_HR(long Size) : this()
        {
            _Size = Size;
            m_OBJ_OVDIM_IM_SHINUY_HR = new OBJ_OVDIM_IM_SHINUY_HR[Size];
        }
        
        public COLL_OVDIM_IM_SHINUY_HR(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }


        public long Count
        {
            get
            {
                return this._Count;
            }
        }
        public void DeleteNullElements()
        {
            m_OBJ_OVDIM_IM_SHINUY_HR = (OBJ_OVDIM_IM_SHINUY_HR[])ArrayHelper.ResizeArray(m_OBJ_OVDIM_IM_SHINUY_HR, _FirstEmpty);
        }
        public void Add(OBJ_OVDIM_IM_SHINUY_HR Object, int ResizeCount)
        {
            if (Object.IsNull) return;

            if (m_OBJ_OVDIM_IM_SHINUY_HR == null)
            {
                m_OBJ_OVDIM_IM_SHINUY_HR = new OBJ_OVDIM_IM_SHINUY_HR[ResizeCount];
                m_OBJ_OVDIM_IM_SHINUY_HR[0] = Object;
                _FirstEmpty = 1;
            }
            else
            {
                if ((((_FirstEmpty) % ResizeCount) == 0) || (_FirstEmpty == m_OBJ_OVDIM_IM_SHINUY_HR.Length ))
                    m_OBJ_OVDIM_IM_SHINUY_HR = (OBJ_OVDIM_IM_SHINUY_HR[])ArrayHelper.ResizeArray(m_OBJ_OVDIM_IM_SHINUY_HR, m_OBJ_OVDIM_IM_SHINUY_HR.Length + ResizeCount);

                m_OBJ_OVDIM_IM_SHINUY_HR[_FirstEmpty] = Object;
                _FirstEmpty++;
            }
            _Count = _FirstEmpty;

        }
        public void Add(OBJ_OVDIM_IM_SHINUY_HR Object)
        {
            if (_Size == 0)
            {
                if (Object.IsNull) return;

                int Size;
                if (m_OBJ_OVDIM_IM_SHINUY_HR == null)
                {
                    m_OBJ_OVDIM_IM_SHINUY_HR = new OBJ_OVDIM_IM_SHINUY_HR[1];
                    m_OBJ_OVDIM_IM_SHINUY_HR[0] = Object;
                }
                else
                {
                    Size = m_OBJ_OVDIM_IM_SHINUY_HR.Length;
                    m_OBJ_OVDIM_IM_SHINUY_HR = (OBJ_OVDIM_IM_SHINUY_HR[])ArrayHelper.ResizeArray(m_OBJ_OVDIM_IM_SHINUY_HR, Size + 1);
                    m_OBJ_OVDIM_IM_SHINUY_HR[Size] = Object;
                }
            }
            else
            {
                m_OBJ_OVDIM_IM_SHINUY_HR[_FirstEmpty] = Object;
                _FirstEmpty++;
            }
                
            _Count = m_OBJ_OVDIM_IM_SHINUY_HR.Length;
        }

        public static COLL_OVDIM_IM_SHINUY_HR Null {
            get {
                COLL_OVDIM_IM_SHINUY_HR obj = new COLL_OVDIM_IM_SHINUY_HR();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleArrayMappingAttribute()]
        public virtual OBJ_OVDIM_IM_SHINUY_HR[] Value {
            get {
                return this.m_OBJ_OVDIM_IM_SHINUY_HR;
            }
            set {
                this.m_OBJ_OVDIM_IM_SHINUY_HR = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            OracleUdt.SetValue(con, pUdt, 0, this.m_OBJ_OVDIM_IM_SHINUY_HR);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.m_OBJ_OVDIM_IM_SHINUY_HR = ((OBJ_OVDIM_IM_SHINUY_HR[])(OracleUdt.GetValue(con, pUdt, 0)));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static COLL_OVDIM_IM_SHINUY_HR Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new COLL_OVDIM_IM_SHINUY_HR();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.COLL_OVDIM_IM_SHINUY_HR")]
    public class COLL_OVDIM_IM_SHINUY_HRFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            COLL_OVDIM_IM_SHINUY_HR obj = new COLL_OVDIM_IM_SHINUY_HR();
            return obj;
        }
        
        public virtual System.Array CreateArray(int length) {
            OBJ_OVDIM_IM_SHINUY_HR[] collElem = new OBJ_OVDIM_IM_SHINUY_HR[length];
            return collElem;
        }
        
        public virtual System.Array CreateStatusArray(int length) {
            return null;
        }
    }
}
