//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSCommon.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class OBJ_YAMEY_AVODA_OVDIM : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private string m_TACHOGRAF;
        
        private decimal m_LINA;
        
        private bool m_LINAIsNull;
        
        private decimal m_BITUL_ZMAN_NESIOT;
        
        private bool m_BITUL_ZMAN_NESIOTIsNull;
        
        private decimal m_UPDATE_OBJECT;
        
        private bool m_UPDATE_OBJECTIsNull;
        
        private System.DateTime m_TAARICH;
        
        private bool m_TAARICHIsNull;
        
        private decimal m_ZMAN_NESIA_HAZOR;
        
        private bool m_ZMAN_NESIA_HAZORIsNull;
        
        private decimal m_HALBASHA;
        
        private bool m_HALBASHAIsNull;
        
        private decimal m_ZMAN_NESIA_HALOCH;
        
        private bool m_ZMAN_NESIA_HALOCHIsNull;
        
        private decimal m_MISPAR_ISHI;
        
        private bool m_MISPAR_ISHIIsNull;
        
        private decimal m_HASHLAMA_LEYOM;
        
        private bool m_HASHLAMA_LEYOMIsNull;

        private int m_SIBAT_HASHLAMA_LEYOM;
        private bool m_SIBAT_HASHLAMA_LEYOMIsNull;

        private long m_MEADKEN_ACHARON;
        private bool m_MEADKEN_ACHARONIsNull;

        private int m_HAMARAT_SHABAT;
        private bool m_HAMARAT_SHABATIsNull;

        public OBJ_YAMEY_AVODA_OVDIM() {
            // TODO : Add code to initialise the object
            this.m_LINAIsNull = true;
            this.m_BITUL_ZMAN_NESIOTIsNull = true;
            this.m_UPDATE_OBJECTIsNull = true;
            this.m_TAARICHIsNull = true;
            this.m_ZMAN_NESIA_HAZORIsNull = true;
            this.m_HALBASHAIsNull = true;
            this.m_ZMAN_NESIA_HALOCHIsNull = true;
            this.m_MISPAR_ISHIIsNull = true;
            this.m_HASHLAMA_LEYOMIsNull = true;
            this.m_SIBAT_HASHLAMA_LEYOMIsNull = true;
            this.m_MEADKEN_ACHARONIsNull = true;
            this.m_HAMARAT_SHABATIsNull = true;
        }
        
        public OBJ_YAMEY_AVODA_OVDIM(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static OBJ_YAMEY_AVODA_OVDIM Null {
            get {
                OBJ_YAMEY_AVODA_OVDIM obj = new OBJ_YAMEY_AVODA_OVDIM();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("TACHOGRAF")]
        public string TACHOGRAF {
            get {
                return this.m_TACHOGRAF;
            }
            set {
                this.m_TACHOGRAF = value;
            }
        }
        
        [OracleObjectMappingAttribute("LINA")]
        public decimal LINA {
            get {
                return this.m_LINA;
            }
            set {
                this.m_LINA = value;
                this.m_LINAIsNull = false;
            }
        }
        
        public bool LINAIsNull {
            get {
                return this.m_LINAIsNull;
            }
            set {
                this.m_LINAIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("BITUL_ZMAN_NESIOT")]
        public decimal BITUL_ZMAN_NESIOT {
            get {
                return this.m_BITUL_ZMAN_NESIOT;
            }
            set {
                this.m_BITUL_ZMAN_NESIOT = value;
                this.m_BITUL_ZMAN_NESIOTIsNull = false;
            }
        }
        
        public bool BITUL_ZMAN_NESIOTIsNull {
            get {
                return this.m_BITUL_ZMAN_NESIOTIsNull;
            }
            set {
                this.m_BITUL_ZMAN_NESIOTIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("UPDATE_OBJECT")]
        public decimal UPDATE_OBJECT {
            get {
                return this.m_UPDATE_OBJECT;
            }
            set {
                this.m_UPDATE_OBJECT = value;
                this.m_UPDATE_OBJECTIsNull = false;
            }
        }
        
        public bool UPDATE_OBJECTIsNull {
            get {
                return this.m_UPDATE_OBJECTIsNull;
            }
            set {
                this.m_UPDATE_OBJECTIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("TAARICH")]
        public System.DateTime TAARICH {
            get {
                return this.m_TAARICH;
            }
            set {
                this.m_TAARICH = value;
                this.m_TAARICHIsNull = false;
            }
        }
        
        public bool TAARICHIsNull {
            get {
                return this.m_TAARICHIsNull;
            }
            set {
                this.m_TAARICHIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ZMAN_NESIA_HAZOR")]
        public decimal ZMAN_NESIA_HAZOR {
            get {
                return this.m_ZMAN_NESIA_HAZOR;
            }
            set {
                this.m_ZMAN_NESIA_HAZOR = value;
                this.m_ZMAN_NESIA_HAZORIsNull = false;
            }
        }
        
        public bool ZMAN_NESIA_HAZORIsNull {
            get {
                return this.m_ZMAN_NESIA_HAZORIsNull;
            }
            set {
                this.m_ZMAN_NESIA_HAZORIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("HALBASHA")]
        public decimal HALBASHA {
            get {
                return this.m_HALBASHA;
            }
            set {
                this.m_HALBASHA = value;
                this.m_HALBASHAIsNull = false;
            }
        }
        
        public bool HALBASHAIsNull {
            get {
                return this.m_HALBASHAIsNull;
            }
            set {
                this.m_HALBASHAIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("ZMAN_NESIA_HALOCH")]
        public decimal ZMAN_NESIA_HALOCH {
            get {
                return this.m_ZMAN_NESIA_HALOCH;
            }
            set {
                this.m_ZMAN_NESIA_HALOCH = value;
                this.m_ZMAN_NESIA_HALOCHIsNull = false;
            }
        }
        
        public bool ZMAN_NESIA_HALOCHIsNull {
            get {
                return this.m_ZMAN_NESIA_HALOCHIsNull;
            }
            set {
                this.m_ZMAN_NESIA_HALOCHIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MISPAR_ISHI")]
        public decimal MISPAR_ISHI {
            get {
                return this.m_MISPAR_ISHI;
            }
            set {
                this.m_MISPAR_ISHI = value;
                this.m_MISPAR_ISHIIsNull = false;
            }
        }
        
        public bool MISPAR_ISHIIsNull {
            get {
                return this.m_MISPAR_ISHIIsNull;
            }
            set {
                this.m_MISPAR_ISHIIsNull = value;
            }
        }

        [OracleObjectMappingAttribute("SIBAT_HASHLAMA_LEYOM")]
        public int SIBAT_HASHLAMA_LEYOM
        {
            get {
                return this.m_SIBAT_HASHLAMA_LEYOM;
            }
            set {
                this.m_SIBAT_HASHLAMA_LEYOM = value;
                this.m_SIBAT_HASHLAMA_LEYOMIsNull = false;
            }
        }

        public bool SIBAT_HASHLAMA_LEYOMIsNull
        {
            get {
                return this.m_SIBAT_HASHLAMA_LEYOMIsNull;
            }
            set {
                this.m_SIBAT_HASHLAMA_LEYOMIsNull = value;
            }
        }

        [OracleObjectMappingAttribute("HAMARAT_SHABAT")]
        public int HAMARAT_SHABAT
        {
            get
            {
                return this.m_HAMARAT_SHABAT;
            }
            set
            {
                this.m_HAMARAT_SHABAT = value;
                this.m_HAMARAT_SHABATIsNull = false;
            }
        }

        public bool HAMARAT_SHABATIsNull
        {
            get
            {
                return this.m_HAMARAT_SHABATIsNull;
            }
            set
            {
                this.m_HAMARAT_SHABATIsNull = value;
            }
        }
        [OracleObjectMappingAttribute("MEADKEN_ACHARON")]
        public long MEADKEN_ACHARON
        {
            get {
                return this.m_MEADKEN_ACHARON;
            }
            set {
                this.m_MEADKEN_ACHARON = value;
                this.m_MEADKEN_ACHARONIsNull = false;
            }
        }

        public bool MEADKEN_ACHARONIsNull
        {
            get {
                return this.m_MEADKEN_ACHARONIsNull;
            }
            set {
                this.m_MEADKEN_ACHARONIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("HASHLAMA_LEYOM")]
        public decimal HASHLAMA_LEYOM {
            get {
                return this.m_HASHLAMA_LEYOM;
            }
            set {
                this.m_HASHLAMA_LEYOM = value;
                this.m_HASHLAMA_LEYOMIsNull = false;
            }
        }
        
        public bool HASHLAMA_LEYOMIsNull {
            get {
                return this.m_HASHLAMA_LEYOMIsNull;
            }
            set {
                this.m_HASHLAMA_LEYOMIsNull = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TACHOGRAF", this.TACHOGRAF);
            if ((LINAIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "LINA", this.LINA);
            }
            if ((BITUL_ZMAN_NESIOTIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "BITUL_ZMAN_NESIOT", this.BITUL_ZMAN_NESIOT);
            }
            if ((UPDATE_OBJECTIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "UPDATE_OBJECT", this.UPDATE_OBJECT);
            }
            if ((TAARICHIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TAARICH", this.TAARICH);
            }
            if ((ZMAN_NESIA_HAZORIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ZMAN_NESIA_HAZOR", this.ZMAN_NESIA_HAZOR);
            }
            if ((HALBASHAIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "HALBASHA", this.HALBASHA);
            }
            if ((ZMAN_NESIA_HALOCHIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ZMAN_NESIA_HALOCH", this.ZMAN_NESIA_HALOCH);
            }
            if ((MISPAR_ISHIIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MISPAR_ISHI", this.MISPAR_ISHI);
            }
            if ((SIBAT_HASHLAMA_LEYOMIsNull == false)){
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SIBAT_HASHLAMA_LEYOM", this.SIBAT_HASHLAMA_LEYOM);
            }
            if ((HAMARAT_SHABATIsNull == false)){            
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "HAMARAT_SHABAT", this.HAMARAT_SHABAT);
            }
            
            if ((MEADKEN_ACHARONIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MEADKEN_ACHARON", this.MEADKEN_ACHARON);
            }
            
            if ((HASHLAMA_LEYOMIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "HASHLAMA_LEYOM", this.HASHLAMA_LEYOM);
            }
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.TACHOGRAF = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TACHOGRAF")));
            this.LINAIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "LINA");
            if ((LINAIsNull == false)) {
                this.LINA = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "LINA")));
            }
            this.BITUL_ZMAN_NESIOTIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "BITUL_ZMAN_NESIOT");
            if ((BITUL_ZMAN_NESIOTIsNull == false)) {
                this.BITUL_ZMAN_NESIOT = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "BITUL_ZMAN_NESIOT")));
            }
            this.UPDATE_OBJECTIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "UPDATE_OBJECT");
            if ((UPDATE_OBJECTIsNull == false)) {
                this.UPDATE_OBJECT = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "UPDATE_OBJECT")));
            }
            this.TAARICHIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "TAARICH");
            if ((TAARICHIsNull == false)) {
                this.TAARICH = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TAARICH")));
            }
            this.ZMAN_NESIA_HAZORIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ZMAN_NESIA_HAZOR");
            if ((ZMAN_NESIA_HAZORIsNull == false)) {
                this.ZMAN_NESIA_HAZOR = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ZMAN_NESIA_HAZOR")));
            }
            this.HALBASHAIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "HALBASHA");
            if ((HALBASHAIsNull == false)) {
                this.HALBASHA = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "HALBASHA")));
            }
            this.ZMAN_NESIA_HALOCHIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ZMAN_NESIA_HALOCH");
            if ((ZMAN_NESIA_HALOCHIsNull == false)) {
                this.ZMAN_NESIA_HALOCH = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ZMAN_NESIA_HALOCH")));
            }
            this.MISPAR_ISHIIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MISPAR_ISHI");
            if ((MISPAR_ISHIIsNull == false)) {
                this.MISPAR_ISHI = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MISPAR_ISHI")));
            }
            this.SIBAT_HASHLAMA_LEYOMIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "SIBAT_HASHLAMA_LEYOM");
            if ((SIBAT_HASHLAMA_LEYOMIsNull == false))
            {
                this.SIBAT_HASHLAMA_LEYOM = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SIBAT_HASHLAMA_LEYOM")));
            }

            this.HAMARAT_SHABATIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "HAMARAT_SHABAT");
            if ((HAMARAT_SHABATIsNull == false))
            {
                this.HAMARAT_SHABAT = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "HAMARAT_SHABAT")));
            }

            this.MEADKEN_ACHARONIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MEADKEN_ACHARON");
            if ((MEADKEN_ACHARONIsNull == false))
            {
                this.MEADKEN_ACHARON = ((long)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MEADKEN_ACHARON")));
            }
            
            this.HASHLAMA_LEYOMIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "HASHLAMA_LEYOM");
            if ((HASHLAMA_LEYOMIsNull == false)) {
                this.HASHLAMA_LEYOM = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "HASHLAMA_LEYOM")));
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static OBJ_YAMEY_AVODA_OVDIM Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new OBJ_YAMEY_AVODA_OVDIM();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.OBJ_YAMEY_AVODA_OVDIM")]
    public class OBJ_YAMEY_AVODA_OVDIMFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            OBJ_YAMEY_AVODA_OVDIM obj = new OBJ_YAMEY_AVODA_OVDIM();
            return obj;
        }
    }
}
