//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSCommon.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class OBJ_LOG_DAY_KELET : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private System.DateTime m_TAARICH;
        
        private bool m_TAARICHIsNull;
        
        private int m_KOD_SHINUY;
        
        private bool m_KOD_SHINUYIsNull;
        
        private int m_MISPAR_ISHI;
        
        private bool m_MISPAR_ISHIIsNull;
        
        private int m_MEADKEN_ACHARON;
        
        private bool m_MEADKEN_ACHARONIsNull;
        
        private System.DateTime m_TAARICH_IDKUN_ACHARON;
        
        private bool m_TAARICH_IDKUN_ACHARONIsNull;
        
        private string m_NEW_VAL;

        private int m_MISPAR_SIDURI_LOG;

        private bool m_MISPAR_SIDURI_LOGIsNull;
        
        private string m_OLD_VAL;
        
        private int m_SEDER_BIZUA;
        
        private bool m_SEDER_BIZUAIsNull;

        private int m_SADE;

        private bool m_SADEIsNull;

        private string m_HEARA;
        
        public OBJ_LOG_DAY_KELET() {
            // TODO : Add code to initialise the object
            this.m_TAARICHIsNull = true;
            this.m_KOD_SHINUYIsNull = true;
            this.m_MISPAR_ISHIIsNull = true;
            this.m_MEADKEN_ACHARONIsNull = true;
            this.m_TAARICH_IDKUN_ACHARONIsNull = true;
            this.m_MISPAR_SIDURI_LOGIsNull = true;
            this.m_SEDER_BIZUAIsNull = true;
            this.m_SADEIsNull = true;
        }
        
        public OBJ_LOG_DAY_KELET(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static OBJ_LOG_DAY_KELET Null {
            get {
                OBJ_LOG_DAY_KELET obj = new OBJ_LOG_DAY_KELET();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("TAARICH")]
        public System.DateTime TAARICH {
            get {
                return this.m_TAARICH;
            }
            set {
                this.m_TAARICH = value;
                this.m_TAARICHIsNull = false;
            }
        }
        
        public bool TAARICHIsNull {
            get {
                return this.m_TAARICHIsNull;
            }
            set {
                this.m_TAARICHIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("KOD_SHINUY")]
        public int KOD_SHINUY {
            get {
                return this.m_KOD_SHINUY;
            }
            set {
                this.m_KOD_SHINUY = value;
                this.m_KOD_SHINUYIsNull = false;
            }
        }
        
        public bool KOD_SHINUYIsNull {
            get {
                return this.m_KOD_SHINUYIsNull;
            }
            set {
                this.m_KOD_SHINUYIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MISPAR_ISHI")]
        public int MISPAR_ISHI {
            get {
                return this.m_MISPAR_ISHI;
            }
            set {
                this.m_MISPAR_ISHI = value;
                this.m_MISPAR_ISHIIsNull = false;
            }
        }
        
        public bool MISPAR_ISHIIsNull {
            get {
                return this.m_MISPAR_ISHIIsNull;
            }
            set {
                this.m_MISPAR_ISHIIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("MEADKEN_ACHARON")]
        public int MEADKEN_ACHARON {
            get {
                return this.m_MEADKEN_ACHARON;
            }
            set {
                this.m_MEADKEN_ACHARON = value;
                this.m_MEADKEN_ACHARONIsNull = false;
            }
        }
        
        public bool MEADKEN_ACHARONIsNull {
            get {
                return this.m_MEADKEN_ACHARONIsNull;
            }
            set {
                this.m_MEADKEN_ACHARONIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("TAARICH_IDKUN_ACHARON")]
        public System.DateTime TAARICH_IDKUN_ACHARON {
            get {
                return this.m_TAARICH_IDKUN_ACHARON;
            }
            set {
                this.m_TAARICH_IDKUN_ACHARON = value;
                this.m_TAARICH_IDKUN_ACHARONIsNull = false;
            }
        }
        
        public bool TAARICH_IDKUN_ACHARONIsNull {
            get {
                return this.m_TAARICH_IDKUN_ACHARONIsNull;
            }
            set {
                this.m_TAARICH_IDKUN_ACHARONIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("NEW_VAL")]
        public string NEW_VAL {
            get {
                return this.m_NEW_VAL;
            }
            set {
                this.m_NEW_VAL = value;
            }
        }
        
        [OracleObjectMappingAttribute("MISPAR_SIDURI")]
        public int MISPAR_SIDURI {
            get {
                return this.m_MISPAR_SIDURI_LOG;
            }
            set {
                this.m_MISPAR_SIDURI_LOG = value;
                this.m_MISPAR_SIDURI_LOGIsNull = false;
            }
        }
        
        public bool MISPAR_SIDURIIsNull {
            get {
                return this.m_MISPAR_SIDURI_LOGIsNull;
            }
            set {
                this.m_MISPAR_SIDURI_LOGIsNull = value;
            }
        }
        
        [OracleObjectMappingAttribute("OLD_VAL")]
        public string OLD_VAL {
            get {
                return this.m_OLD_VAL;
            }
            set {
                this.m_OLD_VAL = value;
            }
        }
        
        [OracleObjectMappingAttribute("HEARA")]
        public string HEARA
        {
            get {
                return this.m_HEARA;
            }
            set {
                this.m_HEARA = value;
            }
        }
        
        

        [OracleObjectMappingAttribute("SEDER_BIZUA")]
        public int SEDER_BIZUA {
            get {
                return this.m_SEDER_BIZUA;
            }
            set {
                this.m_SEDER_BIZUA = value;
                this.m_SEDER_BIZUAIsNull = false;
            }
        }

      
        public bool SEDER_BIZUAIsNull {
            get {
                return this.m_SEDER_BIZUAIsNull;
            }
            set {
                this.m_SEDER_BIZUAIsNull = value;
            }
        }

        [OracleObjectMappingAttribute("SADE")]
        public int SADE
        {
            get
            {
                return this.m_SADE;
            }
            set
            {
                this.m_SADE  = value;
                this.m_SADEIsNull = false;
            }
        }

        public bool SADEIsNull
        {
            get
            {
                return this.m_SADEIsNull;
            }
            set
            {
                this.m_SADEIsNull = value;
            }
        }

        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            if ((TAARICHIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TAARICH", this.TAARICH);
            }
            if ((KOD_SHINUYIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "KOD_SHINUY", this.KOD_SHINUY);
            }
            if ((MISPAR_ISHIIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MISPAR_ISHI", this.MISPAR_ISHI);
            }
            if ((MEADKEN_ACHARONIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MEADKEN_ACHARON", this.MEADKEN_ACHARON);
            }
            if ((TAARICH_IDKUN_ACHARONIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "TAARICH_IDKUN_ACHARON", this.TAARICH_IDKUN_ACHARON);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "NEW_VAL", this.NEW_VAL);
            if ((MISPAR_SIDURIIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "MISPAR_SIDURI", this.MISPAR_SIDURI);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "OLD_VAL", this.OLD_VAL);
            if ((SEDER_BIZUAIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SEDER_BIZUA", this.SEDER_BIZUA);
            }
            if ((SADEIsNull == false))
            {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "SADE", this.SADE);
            }
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "HEARA", this.HEARA);
          
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.TAARICHIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "TAARICH");
            if ((TAARICHIsNull == false)) {
                this.TAARICH = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TAARICH")));
            }
            this.KOD_SHINUYIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "KOD_SHINUY");
            if ((KOD_SHINUYIsNull == false)) {
                this.KOD_SHINUY = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "KOD_SHINUY")));
            }
            this.MISPAR_ISHIIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MISPAR_ISHI");
            if ((MISPAR_ISHIIsNull == false)) {
                this.MISPAR_ISHI = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MISPAR_ISHI")));
            }
            this.MEADKEN_ACHARONIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MEADKEN_ACHARON");
            if ((MEADKEN_ACHARONIsNull == false)) {
                this.MEADKEN_ACHARON = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MEADKEN_ACHARON")));
            }
            this.TAARICH_IDKUN_ACHARONIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "TAARICH_IDKUN_ACHARON");
            if ((TAARICH_IDKUN_ACHARONIsNull == false)) {
                this.TAARICH_IDKUN_ACHARON = ((System.DateTime)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "TAARICH_IDKUN_ACHARON")));
            }
            this.NEW_VAL = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "NEW_VAL")));
            this.MISPAR_SIDURIIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "MISPAR_SIDURI");
            if ((MISPAR_SIDURIIsNull == false)) {
                this.MISPAR_SIDURI = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "MISPAR_SIDURI")));
            }
            this.OLD_VAL = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "OLD_VAL")));
            this.SEDER_BIZUAIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "SEDER_BIZUA");
            if ((SEDER_BIZUAIsNull == false)) {
                this.SEDER_BIZUA = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SEDER_BIZUA")));
            }
            this.SADEIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "SADE");
            if ((SADEIsNull == false))
            {
                this.SADE = ((int)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "SADE")));
            }
            this.HEARA = ((string)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "HEARA")));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static OBJ_LOG_DAY_KELET Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new OBJ_LOG_DAY_KELET();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("KDSADMIN.OBJ_LOG_DAY_KELET")]
    public class OBJ_LOG_DAY_KELETFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            OBJ_LOG_DAY_KELET obj = new OBJ_LOG_DAY_KELET();
            return obj;
        }
    }
}
