using System;
namespace KdsLibrary.BL
{
    interface IOvdimDAL
    {
        bool CheckPeilutExist(int misparSidur, int misparIshi, DateTime shatSidur, DateTime shatYezia);
        bool CheckSidurExist(int misSidur, int misparIshi, DateTime shatSidur);
        void DeleteHachanotMechonaInsertPeiluyot(int iMisparIshi, int iMisparSidur, DateTime dTaarich, DateTime dShatHatchala, KdsLibrary.UDT.COLL_OBJ_PEILUT_OVDIM oCollPeilutOvdimIns);
        void DeleteInsertKnisotLePeilut(int iMisparIshi, int iMisparSidur, DateTime dTaarich, DateTime dShatHatchala, DateTime dShatYezia, long lMakat, int iMeadken_Acharon, KdsLibrary.UDT.COLL_OBJ_PEILUT_OVDIM oCollPeilutOvdimIns);
        System.Data.DataTable GetActiveWorkers(string sPrefix, DateTime FromDate, DateTime ToDate);
        System.Data.DataTable GetArachimLeOved(int iMisparIshi, DateTime dCardDate);
        int GetCountWorkCardNoShaotLetashlum(DateTime dTarMe, DateTime dTarAd, string sMaamad);
        void GetDakot(int iMerkazErua, int iMikumYaad, DateTime dTarich, ref int iDakot);
        System.Data.DataTable GetErrorOvdim(int iKodHevra, int iKodEzor, int iKodSnif, int iKodMaamad, DateTime dFrom, DateTime dTo);
        System.Data.DataTable GetHeadruyot();
        System.Data.DataTable GetHostoriatMeafyeneLeOved(int iMisparIshi, DateTime dFromTaarich, int iCodeMeafyen);
        System.Data.DataTable GetHostoriatNatunLeOved(int iMisparIshi, DateTime dFromTaarich, int iCodeNatun);
        System.Data.DataTable GetIshurim(KdsLibrary.clGeneral.enDemandType DemandType, int MisparIshi, string Month, KdsLibrary.clGeneral.enMonthlyQuotaForm FormType, string Filter);
        System.Data.DataTable GetLastUpdate(int iMisparIshi, DateTime dCardDate);
        System.Data.DataTable GetLastUpdateData(int iMisparIshi, DateTime dTaarich);
        System.Data.DataTable GetLastUpdator(int iMisparIshi, DateTime dTarich);
        System.Data.DataTable GetMeafyeneyBitzuaLeOved(int iMisparIshi, DateTime dTaarich);
        System.Data.DataTable GetMeafyeneyBitzuaLeOvedAll(int iMisparIshi, DateTime dMeTaarich, DateTime dAdTaarich, int iBreratMechdal);
        System.Data.DataTable GetMeafyenimLeovedLetkufa(int iMisparIshi, DateTime startDate, DateTime endDate);
        string GetMeafyenLeOved(int iMisparIshi, DateTime dTaarich, KdsLibrary.clGeneral.enMeafyeneyOved iKodMeafyen);
        int GetMerkazEruaByKod(int iMisparIshi, int iKodErech, DateTime dateCard);
        void GetMikumShaonInOut(int iMisparIshi, DateTime dTarich, ref int iMikumShaonKnisa, ref int iMikumShaonYetzia);
        System.Data.DataTable GetMonthsHuavarLesacharToOved(int iMisparIshi);
        System.Data.DataTable GetMonthsToOved(int iMisparIshi);
        void GetMontlyAndSharedQuota(int MisparIshi, string Period, ref int MontlyQuota, ref int SharedQuota);
        System.Data.DataTable GetOvdimByName(string sPrefix, string sMisparimRange);
        System.Data.DataTable GetOvdimLefiRikuzim(string sPrefix);
        System.Data.DataTable GetOvdimMisparIshi(string sPrefix, string sMisparimRange);
        System.Data.DataTable GetOvdimToPeriodByCode(int Code, DateTime dFrom, DateTime dTo);
        System.Data.DataTable GetOvdimToUser(string sPrefix, int iUserId);
        System.Data.DataTable GetOvdimToUserByName(string sPrefix, int iUserId);
        System.Data.DataTable GetOvedCards(int iMisparIshi, string sMonth);
        System.Data.DataTable GetOvedCardsInTipul(int iMisparIshi);
        System.Data.DataTable GetOvedDetails(int iMisparIshi, DateTime dTo);
        System.Data.DataTable GetOvedDetailsByTkufa(int iMisparIshi, DateTime dFrom, DateTime dTo);
        System.Data.DataTable GetOvedErrorsCards(int iMisparIshi, DateTime from, DateTime to);
        string GetOvedFullName(int iMisparIshi);
        string GetOvedMisparIshi(string sName);
        void GetOvedSnifAndUnit(int iMisparIshi, ref string sSnif, ref string sUnit);
        System.Data.DataTable GetPakadIdForMasach(int iMasachId);
        System.Data.DataTable GetPeiluyotLeOved(int iMisparIshi, int iMisparSidur, DateTime dTaarichWc, DateTime dShatHatchlaSidur);
        System.Data.DataTable GetPirteyHeadrut(int iMisparIshi, DateTime dTaarich, long iBakashaId);
        System.Data.DataTable GetPirteyHeadrutTemp(ref KdsLibrary.DAL.clTxDal oDal, int iMisparIshi, DateTime dTaarich, long iBakashaId);
        System.Data.DataTable GetPirteyHitkashrut(int iMisparIshi);
        System.Data.DataTable GetPirteyOved(int iMisparIshi, DateTime dTaarich);
        System.Data.DataTable GetPirteyOvedAll(int iMisparIshi, DateTime dTaarich);
        System.Data.DataTable GetPirteyOvedLetkufa(int iMisparIshi, DateTime startDate, DateTime endDate);
        System.Data.DataTable GetRechivim();
        System.Data.DataTable GetRechivimChodshiyim(int iMisparIshi, DateTime dTaarich, long iBakashaId, int iTzuga);
        System.Data.DataTable GetRechivimChodshiyimTemp(ref KdsLibrary.DAL.clTxDal oDal, int iMisparIshi, DateTime dTaarich, long iBakashaId, int iTzuga);
        System.Data.DataTable GetRelevantMonthOfApproval(int MisparIshi);
        void GetRikuzChodshi(int iMisparIshi, DateTime dTaarich, long iBakashaId, int iTzuga, float fErechRechiv45, ref System.Data.DataTable dtRikuz1To10, ref System.Data.DataTable dtRikuz11To20, ref System.Data.DataTable dtRikuz21To31);
        void GetRikuzChodshiTemp(ref KdsLibrary.DAL.clTxDal oDal, int iMisparIshi, DateTime dTaarich, long iBakashaId, int iTzuga, float fErechRechiv45, ref System.Data.DataTable dtRikuz1To10, ref System.Data.DataTable dtRikuz11To20, ref System.Data.DataTable dtRikuz21To31, ref System.Data.DataTable dtAllRikuz);
        System.Data.DataTable getRikuzimLeOved(int iMisparIshi, DateTime taarich);
        System.Data.DataTable GetRitzotChishuv(int iMisparIshi, DateTime dTaarich);
        System.Data.DataTable GetShaotMealMichsa(int iMisparIshi, DateTime dTaarich, long lBakashaId);
        string GetSibaLoLetashlum(int iMisparIshi, DateTime dCardDate, int iMisparSidur, DateTime dSidurFullDate);
        System.Data.DataTable GetSidur(string sidurPositionFirstLast, int iMisparIshi, DateTime dCardDate);
        System.Data.DataTable GetSidurimAndPeilut(int iMisparIshi, DateTime dCardDate);
        int GetStatusIsuk(int FormType, int MisparIshi, string Month);
        System.Data.DataTable GetStatusToOved(int iMisparIshi);
        int GetSugChishuv(int iMisparIshi, DateTime dTaarich, ref long iBakashaId, ref DateTime dTarChishuv);
        string GetSugYechidaLeoved(int iMisparIshi, DateTime dTaarich);
        System.Data.DataTable GetWorkCardNoShaotLetashlum(DateTime dTarMe, DateTime dTarAd, string sMaamad);
        void GetZmanNesiaaOvdim(int iMisparIshi, DateTime dTarich, ref int iZmanNesiaHaloch, ref int iZmanNesiaHazor);
        void InsertBakashaMechutzLemichsa(int iMisparIshi, DateTime dTaarich, int iShaot, string sSiba, int iUserId);
        bool IsCardWasUpdated(int iMisparIshi, DateTime dTaarich);
        void SaveSidurimLeoved(KdsLibrary.UDT.COLL_SIDURIM_OVDIM oCollSidurimOvdimUpd, KdsLibrary.UDT.COLL_YAMEY_AVODA_OVDIM oCollYameyAvodaUpd, KdsLibrary.UDT.COLL_OBJ_PEILUT_OVDIM oCollPeilutOvdimUpd);
        void SetMeasherOMistayeg(int iMisparIshi, DateTime dCardDate, int iMeasherOMistayeg);
        void UpdateIdkunyRashemet(int iMisparIshi, DateTime dCardDate, ref System.Data.DataTable dtPakadim, int iLoginUser, int iStatus);
        bool UpdatePremiaDetails(int MisparIshi, DateTime Taarich, int SugPremia, int DakotPremia, DateTime TaarichIdkun, int MeadkenAcharon, int MisparIshiTrail, DateTime TaarichIdkunTrail, int SugPeula);
        bool UpdateRecordInIshurim(int Bakasha_ID, int KodStatusIshur, int MisparIshi, int KodIshur, DateTime Taarich, int MisparSidur, DateTime StartTime, DateTime EndTime, int NumberOfEntry, int Level, int ConfirmedValue, int ValueToConfirm, string siba, int MainFactor, int SecondaryFactor);
        void UpdZmanNesiaa(int iMisparIshi, DateTime dTarich, int izmaNesiaHaloch, int iZmanNesiaHazor, int meadken_acharon);
    }
}
